### ISSUE TITLE
Only showing 6 nodes when connecting to wallet and selecting a node to stake to

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#1066]
### Description

When I connect my wallet and look for a node to stake to I only see options for up to 6 nodes. It should allow you to select from any of the available nodes in the network as seen in the network page. 

![Screenshot 2024-05-28 at 7 44 18 PM](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/21989138/8eea3d97-08e9-40cd-87ed-4ea6ff47847e)

### Steps to reproduce

See above

### Hedera network

other

### Version

na

### Operating system

None

**Comment by P-yiush07** [comment]
Can you tell the steps to reproduce ?

**Comment by SimiHunjan** [comment]
1. Click on the connect to wallet button top right corner
2. Connect with HashPack wallet
3. Click on change staking
4. View the pop-up window that allows you to select a node or account to stake to
5. Click on the drop down menu for selecting a node and see that you can only select from the 7 listed

The total number of nodes you should be able to select from are the following listed here: https://hashscan.io/mainnet/nodes

**Comment by SimiHunjan** [comment]
oh wait I might have selected testnet and not mainnet

**Comment by SimiHunjan** [comment]
yes that was the case whoops. In that case this node list is accurate :). Closing
