### ISSUE TITLE
Mirrornode returns a total supply of 0 even when some accounts hold the token.

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-mirror-node-explorer#1073]
### Description

The mirrornode returns a total_supply of 0 for the testnet USDC token: [link](https://hashscan.io/testnet/token/0.0.429274?p=1), but this is not accurate as some accounts hold the token: [link](https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274/balances).

### Steps to reproduce

1. Search for this token (0.0.429274) on the Testnet HashScan: https://hashscan.io/testnet/token/0.0.429274?p=1 and check the total supply.
2. Verify that some accounts hold the token: https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274/balances 

### Additional context

![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/101180841/fc69aa22-4db9-417e-9126-039dc656c4a3)

### Hedera network

testnet

### Version

v0.1.0

### Operating system

None

**Comment by ericleponner** [comment]
In [data](https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.429274) returned by mirror node, `total_supply` is "0". So HashScan displays the expected value.
Could you file an issue in mirror-node ?
Closing.

**Comment by se7enarianelabs** [comment]
Done: https://github.com/hashgraph/hedera-mirror-node/issues/8433
