### ISSUE TITLE
Contract Verification in Hedera

### ISSUE THREAD

**Issue by damianlluch** [hashgraph/hedera-mirror-node-explorer#111]
Hello, I have a question. I don't know if this is the right place.

Is there any contract verification in Hedera?

I have managed to deploy a contract using the FileAppendTransaction() function.

But in the block explorer I see something that is unintelligible for me...

https://testnet.dragonglass.me/transactions/00460501151656320700698270653

Thank you!

**Comment by SimiHunjan** [comment]
Hi! 

What do you mean by contract verification?

Do you want to verify the bytecode and the source code of the deployed contract?

Or verify that your contract was deployed to the network?

**Comment by SimiHunjan** [comment]
Linking https://github.com/hashgraph/hedera-mirror-node-explorer/issues/71 and closing for now. If you have any questions, please feel free to open the issue again.
