### ISSUE TITLE
prev/next page buttons jump around, thus are not easy to use

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-mirror-node-explorer#1123]
### Description

Using prev/next buttons (`<` `>`) is unnecessarily difficult as they jump around.  You should be able to place your cursor on next (`>`) and then just click click click to advance through pages (likewise for `<`).  Instead the buttons jump around and you have to look at the cursor to see what you're doing, rather than just remain focused on the panel of transactions (or whatever).

Given that the prev/next/page nav bar is _right_ justified the prev/next buttons should be at the _right_ side of that nav bar.  Then they wouldn't jump around.

### Steps to reproduce

See [Loom video](https://www.loom.com/share/7452c37c74b24accb1d430e68fabc802?sid=bd87809c-3f3d-4e45-bc15-aa329cb966d0) (for swirlds labs only) or just try it. (Ignore how the cursor jumps to the image center between each click - that's a glitch of Loom.  Just focus on where the buttons are please!)

### Hedera network

testnet

### Version

current deployed

### Operating system

None

**Comment by fessmm** [comment]
see https://github.com/hashgraph/hedera-mirror-node-explorer/issues/979
