### ISSUE TITLE
Transaction ID display format

### ISSUE THREAD

**Issue by led-boo** [hashgraph/hedera-mirror-node-explorer#1128]
### Problem

When viewing the transaction ID of any transaction, they are currently formatted using '@' and '.' e.g Transaction
**0.0.1234567@1234567891.010111213141**

Exchanges such as Binance and Coinbase require the format to be modified with '-' 'and '-' when submitting the transaction ID to recover funds sent to an exchange without a memo (which occurs daily).

### Solution

Abstracting this inconvenience away would speed up recovery time for new users and improve the user experience whilst standardising a format across these platforms. 

Change the Transaction ID default display format: 
From **0.0.1234567@1234567891.010111213141**
To **0.0.1234567-1234567891-010111213141**

Binance recovery example:
<img width="709" alt="Screenshot 2024-06-18 at 9 08 32 am" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/115443582/f1fc7bfd-6c53-44f5-b2c4-890390a59743">

**Comment by kantorcodes** [comment]
Great idea!

**Comment by svienot** [comment]
Suggested approach:

Add a pull-down menu to the TransactionDetails view, allowing to switch from one ID display format to the other.
The choice then applies across the whole UI, and is persisted in the browser local storage.

<img width="1234" alt="Screenshot 2024-07-11 at 10 37 59" src="https://github.com/user-attachments/assets/8ed019fe-ee3b-4e1c-b2f9-8a80b868ceb0">

<img width="1234" alt="Screenshot 2024-07-11 at 10 37 49" src="https://github.com/user-attachments/assets/e1b3a9d9-122a-4f3f-a675-b9efb0fb3b0a">

**Comment by led-boo** [comment]
This is a great implementation. My only suggestion is the average user would not know the difference according to the labels used. Something simpler like Default format and Exchange format or Recovery format to give it more context for the user. 

Technically the only time a user would use this '-' and '-' is for interacting the an exchange recovery form.

**Comment by svienot** [comment]
thanks for your input @led-boo -- we adopted your suggestion 'Default format' / 'Exchange format'
should be live shortly.

**Comment by led-boo** [comment]
Thank you for this implementation. Users will find it much easier to copy/paste this format without having to manually amend characters.
