### ISSUE TITLE
Confusing message when interacting with Smart Contract via Hashscan

### ISSUE THREAD

**Issue by Burstall** [hashgraph/hedera-mirror-node-explorer#1129]
### Problem

![Screenshot 2024-06-17 220628](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/77861333/61a6003b-7a0e-463b-952f-9db72260d812)

The icon of a red X is confusing as it is displayed on both success & failure.

### Solution

A better visual signal to differentiate would be great (or a more neutral icon).

**Comment by ericleponner** [comment]
Indeed. Thanks for reporting @Burstall.

**Comment by Burstall** [comment]
https://hashscan.io/testnet/contract/0.0.4448124

I engaged with the released / releasable method for token: 0x000000000000000000000000000000000043df78
