### ISSUE TITLE
Display the list of recent transactions for a given NFT serial number

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node-explorer#12]

**Comment by bmgentile** [comment]
+1 can't see NFT transactions between accounts today — would be great to see this information in the "Crypto Transfer" transactions.

**Comment by svienot** [comment]
@bmgentile: Just to make sure I understand what you would like to see...
We do show the NFT/token transfers in the CRYPTO TRANSFER transactions details.
E.g. https://hashscan.io/#/testnet/transaction/0.0.532984-1661497202-658013373

**Comment by bmgentile** [comment]
Hey @svienot — for this one, if I go to check out a specific token ID (NFT) here: https://hashscan.io/#/mainnet/token/0.0.1099105 it shows a list of serial numbers representing each serialized token — I'm curious if there's a way to view each individual token and the transactions which have occurred for each one.

**Comment by svienot** [comment]
Yes, we could select a serial #, and navigate to a page containing a list of recent transactions for that serial #, obtained via this API call:   /api/v1/tokens/<tokenID>/nfts/<serial #>/transactions

**Comment by bmgentile** [comment]
perfect yes that'd be great

**Comment by bmgentile** [comment]
Awesome! Yeah I think that would be useful for the community — essentially you can take a historical look at a single serialized NFTs provenance over time.

**Comment by Sheng-Long** [comment]
closed with #692
