### ISSUE TITLE
Timestamp display should include timezone

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#123]
### Problem

It's frustrating having to convert UTC time for transaction timestamps using this Hedera network explorer.

### Solution

1. Display timestamps in an end user's local timezone automatically
   - Pull this directly from their OS, if possible, rather than through the network (in case they're using a VPN)
   
2. Create a configuration drop-down in the navigation for timezone
   - Maybe display next to ℏ or tℏ

### Alternatives

None

**Comment by ericleponner** [comment]
Timestamp should normally be displayed in navigator-configured timezone.
Using Safari, from France, I see consensus timestamp in french time zone.

For example:
https://hashscan.io/#/mainnet/transaction/0.0.19853-1657578243-934952616?t=1657578253.430362000
displays:
Consensus at:  12:24:13.4303 AM Jul 12, 2022
in my case.

What value does Explorer display in your case ?
Which navigator are you using ?

**Comment by bmgentile** [comment]
Ah this is displaying now in my timezone — I'm using HashScan and double-checked on HederaExplorer, as well.

In addition to this, can/should we look into displaying the timezone acronym next to the time?

**Comment by mohsin-hedera** [comment]
@ericleponner is it possible to display the timezone next to this timestamp ? e.g.
12:24:13.4303 AM Jul 12, 2022 **EST**

**Comment by ericleponner** [comment]
Ok, we'll add timezone.
