### ISSUE TITLE
Staking Demo Feedback

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#125]
### Problem

- [x] It would be great to add some explainer information next to the fields in the staking popup. I.e. - declining the reward - what does it actually mean? What will happen to my reward? etc
like a question mark with a tooltip
- [x] Change “Payed Reward” to “Paid Rewards”?
- [x] Change “Transactions That Payed Reward” to “Staking Rewards Transactions”?
- [x] Change "Decline Reward" = false to "Rewards Acceptance” to be either “Accepted" or Declined”?

### Solution

See above

**Comment by svienot** [comment]
a/ when the user has selected to stake to another account, the following message is displayed next to it:
"Rewards will now be paid to that account.".
b/ the table is titled "Recent Staking Rewards Transactions"
c/ in the account details, we display either "Rewards:  Accepted or "Rewards:  Declined"
