### ISSUE TITLE
Token (NFT) metadata not visible if not suitable for image render

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node-explorer#1269]
### Description

I have created an NFT with metadata that doesn't resolve to an image (https://hashscan.io/testnet/token/0.0.4686859/1), given this, the NFT's metadata doesn't appear to be visible anywhere.

I would expect that in the event an image can't be rendered, the raw metadata would be available in the UI.
(maybe we should show the raw metadata and optionally an image if it can be rendered ?)

### Steps to reproduce

Follow this link: https://hashscan.io/testnet/token/0.0.4686859/1

### Hedera network

testnet

### Version

 v24.4.0-195

### Operating system

None

**Comment by ericleponner** [comment]
Looking at [token info](https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.4686859) returned by mirror node, I see:

```
   ...
    "metadata": "",
   ...
```
shouldn't it be initialized ?

**Comment by svienot** [comment]
I suggest to always show the content of the (raw) metadata property in the NFT.
So in the present case, we'll get this:
<img width="997" alt="Screenshot 2024-08-19 at 15 28 42" src="https://github.com/user-attachments/assets/735753bd-5fb7-4f28-bbd2-dd2d8c78b6a2">
<img width="997" alt="Screenshot 2024-08-19 at 15 28 52" src="https://github.com/user-attachments/assets/96de76d9-011d-4315-85ae-95ea36b42626">
