### ISSUE TITLE
Filter transactions by time & allow for a longer list of transactions in view

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#134]
### Problem

I'm frustrated when, in viewing transactions for a specific entity, I have to click the right arrow many times to see historical data.

### Solution

1. Add date/time range fields next to the transaction "Types" drop-down menu — this would let a user input a date / time range in which they can view transactions for that entity.

2. Allow a user to display more than 10 transactions for a given entity in one view — 10, 20, 50, 100, etc. in a drop-down menu, next to the "page numbers", at the bottom right of the "Recent Transactions" box

### Alternatives

None

**Comment by mohsin-hedera** [comment]
> We have improved table pagination in HashScan : it's now possible to "goto next page until there is no more data".
> When user reaches last page, HashScan checks if more data are available and updates pagination bar to enable more fetching.

**Comment by SimiHunjan** [comment]
Day/time filter can be applied at the account level.

**Comment by mohsin-hedera** [comment]
As shared, it would be of interest, if we can narrow the list of transactions within a start/end timestamp. Especially important for SC where there may be 100s of transactions per minute.

**Comment by Sheng-Long** [comment]
Splitting Issue into #908 and #907.  Closing this issue
