### ISSUE TITLE
View account which created the account I'm viewing

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#135]
### Problem

Looking at an account, I cannot presently find the transaction that created it.

### Solution

1. When viewing an account, add a field that indicates which account created the account I'm viewing.

### Alternatives

None

**Comment by svienot** [comment]
We currently do not have a way to make this kind of query with the mirror-node.

**Comment by Nana-EC** [comment]
@svienot you should be able to find the transaction that created any non system account with the following mirror node call
`https://<env>.mirrornode.hedera.com/api/v1/accounts/{accountId > 0.0.1000}?order=asc&limit=1` e.g. [on testnet](https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.1001?order=asc&limit=1)
The first entry will be a `CRYPTOCREATEACCOUNT` where the entity matches the desired account and the transaction_id will inform the payer that submitted the transaction i.e. `{payerAccountId}-{validStartSec}-{validStartNs}`
This should cover most cases

**Comment by svienot** [comment]
As I understand, the CRYPTOCREATEACCOUNT transaction will be returned only if that transaction also included some kind of transfer (Hbar or token) to the created account.
Under that condition, we should be able to retrieve the (payer) account originating the creation.
Thank you Nana.

**Comment by Nana-EC** [comment]
Rather, it will always be returned for accounts created in the normal manner i.e. via `CRYPTOCREATEACCOUNT`.
All transactions have some crypto transferred.

For cases where the account was auto created using a crypto transfer and an alias you are right the first transaction won't be a `CRYPTOCREATEACCOUNT`.
In this case it's a `CRYPTOTRANSFER` e.g. [1st transaction related to 0.0.46022656](https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.46022656?order=asc&limit=1) you can still take the payer id of the transaction id as the valid payer of the transaction that created the account.
For validation you can then call `https://{env}.mirrornode.hedera.com/api/v1/transactions/{transactionId}?nonce=1` and you'll see the entity_id matches your desired account e.g `https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.88-1655504248-490970758?nonce=1`

Should the 1st transaction type be neither `CRYPTOCREATEACCOUNT` nor `CRYPTOTRANSFER` with a valid child transaction then indeed you won't be able to determine the desired info.
Currently no such case should occur for non system accounts.

**Comment by svienot** [comment]
But when looking at the highest accountIDs (which we assume are the most recently created ones..), i.e. the top items on the Explorer's 'Accounts' page, we always see accounts for which the returned transaction list is empty. 
For instance the most recent at the time of writing this:
https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.1086610

**Comment by Nana-EC** [comment]
> But when looking at the highest accountIDs (which we assume are the most recently created ones..), i.e. the top items on the Explorer's 'Accounts' page, we always see accounts for which the returned transaction list is empty. For instance the most recent at the time of writing this: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.1086610

Ahh you're right. Hmm. Any suggestions @xin-hedera

**Comment by xin-hedera** [comment]
we can consider adding `created_timestamp` to `/api/v1/accounts` and `/api/v1accounts/:id`. The `created_timestamp` is the consensus timestamp of the corresponding `CRYPTOCREATEACCOUNT` transaction. So for accounts auto-created with alias or created with a 0 initial balance, querying `/api/v1/transactions?timestamp=:timestamp&limit=1` should get what you need.

**Comment by steven-sheehy** [comment]
@svienot If you agree that would work for you can you create a ticket on mirror node repo?

**Comment by svienot** [comment]
@steven-sheehy  Apologies for the delay (vacations). Just logged [this one](https://github.com/hashgraph/hedera-mirror-node/issues/4299).
Thanks folks!

**Comment by svienot** [comment]
@bmgentile: would you like to see both the _creator account ID_ and the _create transaction ID_ or is it enough to be able to see the create transaction ?
Below 2 examples of what we could do:

<img width="595" alt="Screenshot 2022-09-30 at 17 03 48" src="https://user-images.githubusercontent.com/16097111/193299664-75c69773-2529-4b2d-9956-d0a8de452adf.png">
<img width="595" alt="Screenshot 2022-09-30 at 17 02 08" src="https://user-images.githubusercontent.com/16097111/193299743-2e9773de-eb45-4b6a-8f6d-bcb29c6f7035.png">

Let us know what you prefer.
