### ISSUE TITLE
Token associate transaction information

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#136]
### Description

An associate token transaction does not tell me what token ID was associated to the account.

For example: https://hashscan.io/#/mainnet/transaction/0.0.836838-1658250170-810672052?type=

### Steps to reproduce

1. Visit a token associate transaction, such as: https://hashscan.io/#/mainnet/transaction/0.0.836838-1658250170-810672052?type=
2. See that it does not show what token was associated with the account.

### Hedera network

mainnet, testnet, previewnet

### Version

Built Thu, 14 Jul 2022 22:31:11 GMT

### Operating system

macOS

**Comment by ericleponner** [comment]
Explorer uses the following mirror node api to get transaction details:
https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.836838-1658250170-810672052
Response does not include associated token.

Explorer is bound to mirror node capabilities.
If you think this information is mandatory, then mirror node must be enhanced first.

**Comment by Neurone** [comment]
Already WIP for Mirror Node REST API (https://github.com/hashgraph/hedera-mirror-node/issues/4142).

**Comment by bmgentile** [comment]
Hey folks has the mirror node been updated to allow for this yet?

**Comment by steven-sheehy** [comment]
> Hey folks has the mirror node been updated to allow for this yet?

Yes, awhile ago. It's available on mainnet mirror node.

**Comment by bmgentile** [comment]
Thanks @steven-sheehy — @ericleponner could we look to implement this token associate visibility functionality above?

**Comment by ericleponner** [comment]
We'll do that asap :)
