### ISSUE TITLE
Separate stake and stake % to two different columns

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#139]
### Problem

Stake and stake percent are together in one column.
![Screen Shot 2022-07-19 at 6 22 13 PM](https://user-images.githubusercontent.com/21989138/179875278-da0dc334-1906-4253-997c-e6ae23bc612c.png)
 

### Solution

Separate the two values into different columns.

**Comment by svienot** [comment]
We have improved the formatting, which hopefully makes data more legible.
As things stand, we show data according to spec, so I am closing the issue.
Let's re-open it if we get evidence that this is not suitable.
