### ISSUE TITLE
Tokens - render custom fees if applicable

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node-explorer#15]
Submitted by [gregscullard](https://github.com/gregscullard):
Should we show custom fees for tokens on the token details page ?
e.g.: http://localhost:8080/#/mainnet/token/0.0.793100 (not suggesting this token has custom fees, merely highlighting the page where they should optionally show)

**Comment by ericleponner** [comment]
Token 0.0.48469453 has custom fees:
[https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.48469453](https://testnet.mirrornode.hedera.com/api/v1/tokens/0.0.48469453)
