### ISSUE TITLE
Improve search by account alias result when the account doesn't exist

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node-explorer#164]
### Problem

When searching by a hex alias which is not activated yet, hashscan show the following message:

"Search error
Server reported errors during the search execution.
This might be transient. Try to search again in a few moments."

it's more user friendly to show a message similar to "The account with the alias doesn't exist."

### Solution

Improve the message when the mirrornode rest api returns 404 when searching by alias.

**Comment by ericleponner** [comment]
In fact, Explorer already checks for 404 and displays a nice message.
But there is a bug when searched value is hex.
So I re-qualified this issue as a bug.
