### ISSUE TITLE
Smart Contract Traceability Phase 2

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#210]
### Problem

Flat trace and state trace for contracts were enabled by the [Record Stream v6](https://hips.hedera.com/hip/hip-435) and [Smart Contract Traceability Extension](https://hips.hedera.com/hip/hip-513) HIPs. Flat trace and state trace information for contracts need to be exposed in the mirror node explorer so that developers can easily access this information about their contracts.

Flat Trace:

- [x] Define requirements for contract flat trace feature
- [x] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/211
- [x] Contract flat trace available in staging site
- [x] Contract flat trace view approved by stakeholders
- [x] Contract flat trance view deployed

State Trace:
- [x] Define requirements for contract flat trace feature
- [x] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/212
- [x] Contract state trace available in staging site
- [x] Contract state trace view approved by stakeholders
- [x] Contract state trance view deployed

### Solution

- [x] #245
- [x] #246

**Comment by svienot** [comment]
Closing this since the bulk of work planned has been done. We'll open specific issues for incremental improvements.
