### ISSUE TITLE
Option to sort token holder's by balance

### ISSUE THREAD

**Issue by nubeasado** [hashgraph/hedera-mirror-node-explorer#213]
### Problem

When viewing a fungible token on hashscan (e.g. https://hashscan.io/#/mainnet/token/0.0.731861), it shows a list of 100 wallets which hold it, sorted by account ID. This isn't always entirely useful, especially for tokens which have several thousand accounts associated to it.

### Solution

Add the option on a token's page to sort token holders by the amount they hold.

**Comment by svienot** [comment]
The mirror-node REST API does not (and does not plan to) support sorting by arbitrary fields in general. In the present case, the API support sorting by account ID only.
I suggest we close this issue and it won't be possible to implement in the foreseeable future.
