### ISSUE TITLE
Review DX with addition of community nodes

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#233]
### Problem

Community nodes will be added to the network in the future. The Hedera Mirror Node Explorer UI needs to be updated to accommodate community nodes.

- Evaluate min stake/max stake values
- Differentiation between community nodes vs. council nodes
- Evaluate any other information that may need to be displayed for community nodes

### Solution

- [x] Document community node requirements
- [x] Complete UI design
- [x] Review staging site
- [x] Deploy to production

**Comment by SimiHunjan** [comment]
Community Node Requirements:

- Differentiate between council node and community node
- Community nodes will have different min and max stake values
- The min and max stake values will be populated by Services team

**Comment by SimiHunjan** [comment]
Check to see if the min and max stake bar will accommodate different min and max stake values.

**Comment by SimiHunjan** [comment]
There will be a Hedera Improvement Proposal submitted to have a flag in the address book that will flag which node is a community node vs. a council node.

**Comment by svienot** [comment]
Proposed design for the Nodes page. 
- **Changes**:
  - Added icon to visually differentiate _Council Nodes_ and _Community Nodes_
  - Added columns for _Min Stake_, _Max Stake_
  - Removed _Account_ column, probably not needed at this level
  _- Question: is it useful to keep Last Reward Rate in this table or is it always the same value for all nodes ?_
- **2 Options** for the _Stake Range_ gauge, as shown below:
  - Relative gauge: range from 0 to 1.2 * node-max-stake
  - Absolute gauge: range from 0 to the max of all node-range, node-range being max(node-stake, node-max-stake)

**Option 1** (relative gauges)
<img width="1189" alt="Screenshot 2023-02-16 at 23 46 26" src="https://user-images.githubusercontent.com/16097111/219600635-20dea3aa-0754-4372-9e22-f4f97e5b7db0.png">

**Option 2** (absolute gauges)
<img width="1132" alt="Screenshot 2023-02-16 at 18 53 18" src="https://user-images.githubusercontent.com/16097111/219600712-388984e9-6337-4473-9c23-0479968b4225.png">

**Comment by svienot** [comment]
Proposed design for the Node Details view.

**Changes**:
- A sub-title is added mentioning either _Hedera Council Node_ or _Community Node_
- The mention is preceded by the corresponding icon (which teaches the meaning of the icon).

<img width="1076" alt="Screenshot 2023-02-17 at 13 16 36" src="https://user-images.githubusercontent.com/16097111/219652408-f42d9bfe-b28a-49b7-9ea9-2a7abd8248aa.png">

<img width="1076" alt="Screenshot 2023-02-17 at 13 16 45" src="https://user-images.githubusercontent.com/16097111/219652453-8c260f30-3aba-4d97-9685-d1ab39bec1a3.png">

**Comment by svienot** [comment]
Proposed design for the Staking page and Staking dialog

**Changes**:
- Icon added in front of node currently staked-to, to indicate council vs. community
- Icon added in front of current selection in node selector
- Node selector options grouped in 2 categories (council & community)

<img width="1076" alt="Screenshot 2023-02-17 at 13 48 18" src="https://user-images.githubusercontent.com/16097111/219679773-8a6ddd98-e747-452a-a550-2b76c1dd73b3.png">

<img width="761" alt="Screenshot 2023-02-17 at 15 15 31" src="https://user-images.githubusercontent.com/16097111/219679471-2288b6e3-afe9-405e-9d6c-56189a8ccf07.png">

<img width="709" alt="Screenshot 2023-02-17 at 15 14 45" src="https://user-images.githubusercontent.com/16097111/219679524-ac940eea-d6b8-4b81-9bc5-053b72584189.png">

<img width="1076" alt="Screenshot 2023-02-17 at 15 22 15" src="https://user-images.githubusercontent.com/16097111/219680814-1c25c6f9-1c79-4e94-b2e2-1f32391a55c2.png">

**Comment by SimiHunjan** [comment]
@bmgentile @ed-marquez @sergmetelin any feedback on the proposed experience for community nodes vs. council nodes?

**Comment by SimiHunjan** [comment]
Proposed design for the Nodes view.

- I like Option 2 (absolute gauges)

For the change staking image with the drop list of council and community nodes I don't believe it will be "Hosted by Hedera" for each community node entry. Rather "Hosted by Community."

**Comment by svienot** [comment]
Forgot to mention that I have faked a few community nodes on the nodes returned by the REST API for testnet (HashScan does not touch their description, which comes directly from address book) so, yes the nodes descriptions will look different once we get actual community nodes.

**Comment by bmgentile** [comment]
For the "Enter the number of HBARs you want to stake" — I'm confused by this wording, as I thought that it was the "account" that is staked, inclusive of all HBARs, and not the HBARs individually that are staked. 

@SimiHunjan can you advise on that?

**Comment by bmgentile** [comment]
> @bmgentile @ed-marquez @sergmetelin any feedback on the proposed experience for community nodes vs. council nodes?

I think that the community nodes should be able to "Claim" their node by signing a transaction and be able to update a description, icon, etc. — this might be "phase 2" of this endeavor, but it'd be great to allow them control over what is displayed.

**Comment by SimiHunjan** [comment]
@bmgentile that image is for the rewards calculator. You can enter the value of the HBAR to see how much reward you may get for the number of HBARs entered. https://hashscan.io/mainnet/staking

**Comment by SimiHunjan** [comment]
> I think that the community nodes should be able to "Claim" their node by signing a transaction and be able to update a description, icon, etc. — this might be "phase 2" of this endeavor, but it'd be great to allow them control over what is displayed.

@mohsin-hedera @alikatamjani flagging feature request above for community nodes

**Comment by SimiHunjan** [comment]
Change staking dialog
- We try limiting the information in the drop-down to have who it is hosted by, the type of node operator (community vs. Hedera), and the stake percentage.
