### ISSUE TITLE
Notify users when their contract has entered the contract grace period

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#26]
### Problem

When contracts expire they enter a grace period. When the contract is in the grace period window the contract should display should notify the user that it is in the grace period before the contract is permanently removed. Users can auto renew the contract in this grace period. 

HIP

https://hips.hedera.com/hip/hip-16
https://hips.hedera.com/hip/hip-449

### Solution

Change color on the screen to red or something that signifies the contract is in its grace period.

**Comment by svienot** [comment]
From a UI perspective, would a banner such as this one seem adequate?

<img width="1194" alt="Capture d’écran 2022-05-10 à 15 27 48" src="https://user-images.githubusercontent.com/16097111/167645014-d7f633f9-7c2f-4f22-a328-a5e9eb18fc87.png">
