### ISSUE TITLE
Search for tokens by EVM address

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-mirror-node-explorer#271]
### Problem

I'd like to be able to search for a token when I only possess their EVM address, like a contract.

<img width="1252" alt="Screen Shot 2022-10-23 at 6 25 27 PM" src="https://user-images.githubusercontent.com/11776938/197400868-39af115b-4eb5-4a1e-8524-4b828b26a6b6.png">

### Solution

Searching for a token address should display results properly like searching for a contract.

**Comment by ericleponner** [comment]
This is fixed by PR [00188 + 00271 search account](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/272) …

**Comment by svienot** [comment]
Thanks for reporting this @Cooper-Kunz.
