### ISSUE TITLE
Write a Helm chart for hedera-mirror-node-explorer

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-mirror-node-explorer#282]
### Problem

Coming from an initiative across hashgraph products(repos) we want to run on a cloud managed Kubernetes (GKE, EKE, AKS) that ops creates and manages.
Adding helm chart support has been logged in: https://github.com/hashgraph/hedera-services/issues/4068 
as well as in https://github.com/hashgraph/hedera-local-node/issues/189 
The mirror-node and relay already have this support. They can be referenced as examples.

### Solution

Write a [Helm](https://helm.sh/) chart for local node and manage the deployments.

**Comment by ericleponner** [comment]
Hi Kalina, 
I’m wondering if you targetedthe right repo…
Shouldn’t this request opened on hedera-mirror-node (not hedera-mirror-node-explorer) ?

**Comment by Kalina-Todorova** [comment]
Hi Eric, this should be the correct repo. The [mirror-node](https://github.com/hashgraph/hedera-mirror-node) already has helm chart support. 

We recently integrated the mirror-node-explorer into the [local-node](https://github.com/hashgraph/hedera-local-node) and were discussing a general approach with helm chart support for all (most) projects under hashgraph.

**Comment by ericleponner** [comment]
Thanks for clarifying :)
I need to learn about helm chart.

**Comment by SimiHunjan** [comment]
@steven-sheehy are you able to help assist with creating the helm chart? Otherwise we can focus on that effort.
