### ISSUE TITLE
Staking : Allow users to download rewards and exchange rate information

### ISSUE THREAD

**Issue by mohsin-hedera** [hashgraph/hedera-mirror-node-explorer#287]
### Problem

As a user staking to a Hedera node, 
I would like to receive my rewards transactions including the date and amount of reward in HBar as well as exchange rate information to convert these HBar to fiat
So that I can fulfill my recording keeping and accounting obligations (e.g. capital gains etc.)

### Solution

Suggest we have two additional icons to the Staking Rewards  transactions. 
- To download upto 12 months of rewards transactions at a time
- To download daily HBar/USD rate (e.g. from ERT Tool)
![image](https://user-images.githubusercontent.com/92186249/198718951-1a3f6f61-0d7a-4ccd-ad53-c70cd0355764.png)

### Requires
[ ] https://github.com/hashgraph/hedera-mirror-node/issues/4744

**Comment by ericleponner** [comment]
Regarding transaction history, requirement above lists the following fields:
1) Transaction Time
2) Transaction ID
3) Transaction Type
4) Reward Amount

Upcoming api specified in mirror node [#4744](https://github.com/hashgraph/hedera-mirror-node/issues/4744) will not return 2) and 3).
Mohsin confirmed that these two columns can be omitted.

So CSV output will contain only the two following columns:
1) Transaction Time
4) Reward Amount

**Comment by svienot** [comment]
The CSV download of recent staking rewards information has been implemented.
The addition of exchange rate information as a dependency upon a mirror node API enhancement.
So I am closing this as resolved and opening [#329](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/329) to track the addition of exchange rate info.
