### ISSUE TITLE
Publish docker images

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node-explorer#304]
### Problem

As a developer, I'd like to be able to run the explorer locally in concert with local consensus and mirror nodes. A prerequisite for working on #282.

### Solution

* Add a GitHub workflow that publishes a multi-architecture (arm64/amd64) Docker image to `gcr.io/hedera-registry/hedera-explorer` (See mirror node [example](https://github.com/hashgraph/hedera-mirror-node/blob/01bcf5817d91922035d166761ca6e3d874bb267f/.github/workflows/release-production.yml#L56))
* Tag version and a static `latest` tag
  * Since there are no git tags or releases, the version tag could use [calver](https://calver.org/) or some other incrementing date/time based versioning scheme

**Comment by svienot** [comment]
As requested by Nathan, assigning the issue to him.
