### ISSUE TITLE
Strange parsing of unicode in the metadata field on an NFT serial

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-mirror-node-explorer#326]
### Description

There is some strange parsing of unicode in the metadata field on an NFT serial.

Check for example: https://hashscan.io/mainnet/token/0.0.1443191, you will see strings like `kns:defi.à`

![screenshot_2022-11-17_at_5 12 18_pm](https://user-images.githubusercontent.com/562943/202742038-23e26d96-3f58-4614-84cc-4b601076b831.png)

If you pull the metadata from the mirror node directly, and you parse using a base64 decoder, you get something like `kns:defi.ℏ`

### Steps to reproduce

1.  Go to: https://hashscan.io/mainnet/token/0.0.1443191
2. See the strings in the metadata field

### Hedera network

mainnet, testnet, previewnet

### Version

rolling-release ;)

### Operating system

macOS

**Comment by ericleponner** [comment]
Issue has been fixed in two steps:
1) PR [#321](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/321) fixed the code but broke the tests
2) PR [#287](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/325) fixed the tests

Closing…
