### ISSUE TITLE
Searching tokens by name or symbol

### ISSUE THREAD

**Issue by ghost** [hashgraph/hedera-mirror-node-explorer#33]
### Problem

Being able to search for tokens using the token's name rather than simply the token ID would be useful from a usability standpoint and may be helpful if you do not know the token ID.

### Solution

Support searching tokens using token name, token symbol or token ID

**Comment by svienot** [comment]
The mirror-node REST API currently allows to query tokens by tokenID, not by name or symbol.

**Comment by rbair23** [comment]
I ran into this today as well, it would be a great feature.

**Comment by SimiHunjan** [comment]
Update: We are working on a HIP to enhance the mirror node APIs to enable this feature. Will update with the HIP link when it becomes available.

**Comment by SimiHunjan** [comment]
Mirror node issue: https://github.com/hashgraph/hedera-mirror-node/issues/8115

**Comment by SimiHunjan** [comment]
https://hips.hedera.com/hip/hip-968

**Comment by SimiHunjan** [comment]
Need to identify solutions to show reputable tokens in the community.

**Comment by SimiHunjan** [comment]
Show more will only show 100 results

**Comment by SimiHunjan** [comment]
Search by token name was released. Search by token symbol not possible with mirror node.
