### ISSUE TITLE
Unable to search for transactions by transaction hash on hashscan.io/testnet

### ISSUE THREAD

**Issue by rhysied** [hashgraph/hedera-mirror-node-explorer#348]
### Description

hi,

I'm not sure of the cause of the issue but searching for transactions by transaction hash on the testnet seems to be broken and always returns the "No results" page. I tried adding and removing the "0x" prefix to see if that helped but it didn't. Searching by transaction hash seems to work fine on hashscan.io/mainnet

### Steps to reproduce

1) Go to hashscan.io/testnet and search for a transaction via transaction hash (e.g. https://hashscan.io/testnet/search-result/0x046677b45ecc71dec61c2796952f1931da9c9781bb9fa1e777363ba1be5b7d54a385568602fe6740cf69ab4726c31151)
2) See the "no result" screen. Expected behaviour is that it should forward you on to the correct transaction, e.g. https://hashscan.io/testnet/transaction/0.0.1959103-1670346020-506879899

### Hedera network

testnet

### Version

unknown

### Operating system

macOS

**Comment by ericleponner** [comment]
Search by transaction hash is currently enabled on mainnet mirror node only.
This feature is on-going work. 
You can track this by following [#4364](https://github.com/hashgraph/hedera-mirror-node/issues/4364).

**Comment by svienot** [comment]
Closing this issue since there is no action to take on hashscan/explorer. 
As soon as search transaction by hash is enabled on testnet and previewnet mirror-nodes, hashscan will benefit from it.
