### ISSUE TITLE
explorer no longer accepts only the transaction id

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#368]
### Problem

The mirror node explorer previously allowed for transactions to be searched by tx id by navigating to a URL akin to: https://hashscan.io/testnet/transaction/0.0.123-456-789

But no longer does. Can this functionality be restored?

### Solution

See above

**Comment by mshakeg** [comment]
This would also apply to transaction hashes, i.e. I would like to breakout to a transaction by it's txHash e.g:
https://hashscan.io/testnet/transaction/0x1234....56789

**Comment by ericleponner** [comment]
`transaction_id` is not a unique identifier of a transaction : `timestamp` or `transaction hash` are.
May be you could use one of these two items (?).

Regarding `https://hashscan.io/{network}/transaction/{tx_hash}`, this is enabled on mainnet only.
This is on-going work right now (see [#348](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/348)).

**Comment by mshakeg** [comment]
@ericleponner I see, but `transaction_id` was originally meant to be unique, not sure what changed since, also if it's not meant to be unique why does the hashscan search option allow for searching by txId and then redirect to that tx i.e: `https://hashscan.io/{network}/transaction/{conTimestamp}?tid={accountId}-{seconds}-{nanoseconds}`

Maybe at least have the option to use breakout to a tx by the txId as almost all txIds are unique. This was the case until relatively recently.

**Comment by ericleponner** [comment]
Regarding the search, this is unfinished work : currently HashScan displays the first transaction returned by mirror node.
This is not really satisfying. Search will someday handle case where results are multiple and let user choose.

`transaction_id` false unicity is an old story. Our early architecture choices didn't take that into account.
This became problematic and had to re-organize hashscan code to clarify this unicity issue.

Indeed we removed url `{network}/transaction/{tx_id}`. Couldn't you use `timestamp` ?

**Comment by mshakeg** [comment]
@ericleponner I see.

> Couldn't you use `timestamp`?

I'd have to make a mirror node call to get the consensus `timestamp/s` for that `tx_id` to get a full URL to breakout to. I'd prefer to not have to do that and breakout to hashscan with only the `tx_id` and have an hashscan deal with that accordingly either:
1. show the tx with that `tx_id` if only 1 exists or
2. if multiple txs have the same `tx_id` then a page listing all of those txs

**Comment by mshakeg** [comment]
@ericleponner does the `@hashgraph/sdk` return the `transactionHash` in either the `TransactionResponse` or `TransactionReceipt` or at least expose a method to compute the evm `transactionHash` for an `accountId`? The former would be useful if wallets returned the transactionHash after signing and the latter will work if wallets for whatever return don't return the transactionHash as the hash can still be computed(though will require json rpc call to get the tx count as I believe that's the nonce used to compute the hash) before a tx is signed

**Comment by ericleponner** [comment]
@mshakeg Yes, TransactionResponse includes the transaction hash.

**Comment by mshakeg** [comment]
@ericleponner hashscan doesn't seem to allow transactions to be searched by txHash take for example [this tx](https://hashscan.io/testnet/transaction/1671533784.741762333?tid=0.0.29667223-1671533769-677109004), trying to search for that tx by the txHash listed on hashscan doesn't work

**Comment by ericleponner** [comment]
Yes, that's the problem mentioned above:
_Regarding https://hashscan.io/{network}/transaction/{tx_hash}, this is enabled on mainnet only.
This is on-going work right now (see https://github.com/hashgraph/hedera-mirror-node-explorer/issues/348)._

**Comment by mshakeg** [comment]
@ericleponner I'm able to get the tx by its txHash on the testnet mirror node but only using the 32-byte truncated txHash(not the 48-byte txHash) as per the [discussion here](https://github.com/hashgraph/hedera-json-rpc-relay/issues/757#issuecomment-1370901874).

Is there a reason why I can't search using the 32-byte txHash on _hashscan/testnet_ despite being able to get a tx by its 32-byte hash on the testnet mirror node? Presumably the same call is made by hashscan to the mirror node to get the transaction's info.
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0x5d5dd074e80852c3ffd47571a162fc5fe93135360b45d178bf7b68e88bdebec7

**Comment by steven-sheehy** [comment]
Searching for a contract result by its transaction hash is a separate API call from getting a transaction by its hash. The former is enabled in all environments while the latter is only on mainnet. There are a lot less contract related transactions which is why it's enabled, but eventually that will become a performance concern as well that we will have to address at some point.

**Comment by ericleponner** [comment]
@mshakeg if you have 32 bytes hash (also nicknamed "ethereum hash"), then use this url:
https://hashscan.io/testnet/tx/0x5d5dd074e80852c3ffd47571a162fc5fe93135360b45d178bf7b68e88bdebec7

This URL is part of [EIP 3091](https://eips.ethereum.org/EIPS/eip-3091) and HashScan supports this specification.

**Comment by mshakeg** [comment]
@ericleponner thanks, that's great, I assumed `https://hashscan.io/{network}/transaction/{tx_hash}` would handle both the 32-byte and 48-byte hashes, especially since at least in my understanding the 32-byte hash is a truncation of the 48-byte hash at least for HSCS txs.

**Comment by ericleponner** [comment]
Final words about this issue:
1) `hashscan.io/{network}/transaction/{transaction_id}` is no longer supported
2) `hashscan.io/{network}/tx/{ethereum_hash}` should be used in place

There is no additional action to be done. So I close this issue.
