### ISSUE TITLE
Preserve USD price of HBAR for historic transactions

### ISSUE THREAD

**Issue by Ashe-Oro** [hashgraph/hedera-mirror-node-explorer#407]
### Problem

Hashscan calculates past transaction fee costs using the current hbar price rather than the price of hbar at the time of transaction.   I identified this when going back and reviewing old NFT mints and the prices and they seemed to have changed in USD terms.

This mint was done on Dec 29th when HBAR was ~4c. You can see the new calculation of "Max Fee" is 2hbar which is currently calculated as 10.9c which is the current USD value of HBAR.

https://hashscan.io/testnet/transaction/1672330309.525809135?tid=0.0.49183798-1672330299-446453328&p1=1&k1=1672330329.788503003

![image](https://user-images.githubusercontent.com/5784328/213024274-3f8ce6cb-bc9a-4289-8a28-f60612141387.png)

### Solution

Current: We hold hbar fee constant (obviously), but not the USD fee paid.
Expected: We also hold the USD fees consistent to the price of hbar when the fee was paid.

Note: Etherscan retains the current ETH price on the settlement day, which i what I would expect.

![image](https://user-images.githubusercontent.com/5784328/213024340-11ab0f71-c487-40c0-a2e3-69e8e44bb5de.png)

**Comment by svienot** [comment]
Indeed, when displaying the details of a transaction, we should derive the USD amounts using the rate returned by `/api/v1/network/exchangerate?timestamp={consensusTimestamp}` instead of the current exchange rate.
