### ISSUE TITLE
reverted ETHEREUM TRANSACTION should show same data as CONTRACT CALL tx

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#411]
### Problem

The tx page for reverted txs of type **ETHEREUM TRANSACTION** does not have all the information for txs of type **CONTRACT CALL** despite the mirror node returning all the data required such as `state_changes`, `error_message`, 
 `from`, `function_parameters`  and so on.

Examples of 2 such transactions:
**ETHEREUM TRANSACTION** with many fields NOT showing(despite the mirror node returning all required data):
https://hashscan.io/testnet/transaction/1673808122.180036003?tid=0.0.902-1673808113-111424007

**CONTRACT CALL** with all fields from the mirror node showing:
https://hashscan.io/testnet/tx/0x8a2c694856e1add60d4d000ab44dbe860d51e9b65ec48d3c0689b70a5779a58e

### Solution

The above 2 tx examples are sufficient evidence of the issue. Querying the mirror node for both transactions returns the same fields for both txs. However I did notice that some fields for the **ETHEREUM TRANSACTION** are `null` such as `address`,  `contract_id`, `to`, in addition some fields on the **CONTRACT CALL** are `null` such as `chain_id`; which could have a valid value.

**Comment by ericleponner** [comment]
Indeed there is an issue with the following API call:
https://testnet.mirrornode.hedera.com/api/v1/contracts/`null`/results/1673808122.180036003

Thanks for reporting @mshakeg

**Comment by svienot** [comment]
Correct, we fail to fetch the contract result in that case. 
Note that the wrapped CRYPTO TRANSFER tx (available with the _Child Transaction_ property link shows its contract result.
