### ISSUE TITLE
explorer shows contract has expired and entered grace period

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#420]
### Description

The explorer shows the warning **"Contract has expired and is in grace period"**  for number of contracts that have more than enough HBAR to pay their contract rent such as the following:
* https://hashscan.io/mainnet/contract/0.0.1060875
* https://hashscan.io/mainnet/contract/0.0.1060864

AFAIK contract rent is scheduled for sometime in February, so I don't think the above warning makes sense to show at this point in time.

Also, I think it would be helpful for the contract rent cost to be displayed on the explorer's contract page.
```
Contract Rent = Auto-renewal Cost + Storage(Key-Value) Costs
```

### Steps to reproduce

The above example contracts are sufficient evidence of the issue.

### Hedera network

mainnet

### Version

mirror-node@0.71.0

### Operating system

None

**Comment by svienot** [comment]
This banner should not be displayed indeed on mainnet for the time being.
 As far as showing the contract rent cost, not sure yet which information will be available to HashScan.

**Comment by svienot** [comment]
We will enable this capability soon. In the interim we can educate the users, if they so inquire. For now, we do nothing.

**Comment by mshakeg** [comment]
@svienot I couldn't find an issue on the mirror node pertaining to contract storage so I created [hedera-mirror-node#5761](https://github.com/hashgraph/hedera-mirror-node/issues/5761)
