### ISSUE TITLE
Decode contract error message if it's a string

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node-explorer#434]
### Problem

When I run a smart contract that reverts, there often is a string attached to the revert reason, at the moment, the explorer shows hex values, but could easily convert this to a human readable string

### Solution

If the error message starts with `0x08c379a`, the error contains a string which can be decoded as follows with ethers.js

```
    const reason = ethers.utils.defaultAbiCoder.decode(
        ['string'],
        ethers.utils.hexDataSlice(error, 4)
    )
    console.log(reason);
```

for example, this error `0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d45524332303a20696e73756666696369656e7420616c6c6f77616e6365000000`

translates to

`ERC20: insufficient allowance`

### Alternatives

Let the user/developer figure out how to decode the string

**Comment by svienot** [comment]
Merci @gregscullard for the code, it's a pleasure to implement your suggested enhancements :-)

**Comment by ericleponner** [comment]
Call Trace section in Transaction Detail page contains also an Error Message field that needs the same decoding.
I re-open this issue to track that down.

**Comment by svienot** [comment]
We will decode both Error(string) and Panic(uint256) when present in the error_message field. 

Error(string) example:
<img width="929" alt="Screenshot 2023-03-02 at 22 48 02" src="https://user-images.githubusercontent.com/16097111/222568934-d42d80a0-0720-4c3f-98e9-7b8c51cb18e4.png">

Panic(uint256) example:
<img width="929" alt="Screenshot 2023-03-02 at 22 59 13" src="https://user-images.githubusercontent.com/16097111/222569028-a84a4019-8f76-43a2-9410-3dc83c202775.png">
