### ISSUE TITLE
Improve support for custom networks

### ISSUE THREAD

**Issue by beeradb** [hashgraph/hedera-mirror-node-explorer#439]
### Problem

There is currently support in the mirror node explorer to add a custom network. This support is limited in a few ways:

- Only a single additional network is supported
- there's no way to [override or remove existing defaults](https://github.com/hashgraph/hedera-mirror-node-explorer/blob/main/src/schemas/NetworkRegistry.ts#L48-L67) (mainnet, testnet, previewnet).

This means if you  want to support 5 custom networks, you'd need 5 separate node explorer deployments, and each of them would still contain the default networks in addition to your single custom network.

### Solution

A config file should be added that allows you to add networks, remove networks, or modify the default networks. The defaults for this config file should contain definitions for the existing "production" networks.

We should also document any constraints that may exist by overriding this configuration, such as "It's not recommended to add more than 10 networks due to UI constraints" or "Network names should be 10 characters or less" (just as examples)

**Comment by svienot** [comment]
@beeradb  I assume your deployment(s) of the explorer will be Docker based ?
We have prototyped an approach which allows to provide a JSON configuration file containing the network configuration, located alongside the docker-compose.yml. The syntax is:
```
  {
    "name": "testnet",
    "url": "https://testnet.mirrornode.hedera.com/",
    "ledgerID": "01"
  },
  {
    "name": "mytestnetwork",
    "url": "http://localhost:5551/",
    "ledgerID": "02"
  },
... 
```
When present in a Docker deployment, this file fully controls the list of items in the network menu (and by default contains mainnet/testnet/previewnet).

In a regular (non Docker) deployment, the VueJS based implementation is limited to build-time environment variables; so we would leave things as they are and ignore the content of the JSON network configuration.

**Comment by beeradb** [comment]
@svienot since this is a static site, I think our preferred method would be to mirror production deploys and have the site served out of an S3 bucket. Since we already have the pipelines/automation in place to deploy there, maintaining consistency across environments would be the most seamless experience for us. 

I'm assuming the docker-based solution wouldn't work in this context?

**Comment by svienot** [comment]
I see. No docker-based deploy would not work. OK, we'll need to provide something which works for the static site deploy.
