### ISSUE TITLE
503 error when searching account 0.0.88 on testnet

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#443]
### Problem

When searching for account 0.0.88 on testnet the page did not load. Tried this a couple of times and resulted in the same experience.

![Screenshot 2023-02-13 at 7 27 59 PM](https://user-images.githubusercontent.com/21989138/218631838-57d6d5d8-ea66-4e9e-b073-cb56097d78c3.png)

### Solution

Investigate reasons for error.

**Comment by ericleponner** [comment]
The following call to mirror node:
`https://testnet.mirrornode.hedera.com/api/v1/accounts/0.0.88?limit=1`

return status 503 and the following body:
`{"_status":{"messages":[{"message":"Service unavailable"}]}}`

**Comment by ericleponner** [comment]
I created #5416 to track this mirror node issue.
