### ISSUE TITLE
Define APIs to for the search feature in the mirror node explorer 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#445]
### Problem

Applications would like to use an API to display information about a transaction or entity in the network. The defined API would be maintained and would not break in the future. 

### Solution

Define API.

**Comment by SimiHunjan** [comment]
Linking issue: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/338

**Comment by SimiHunjan** [comment]
Research the options for having these kind of APIs to be supported

**Comment by SimiHunjan** [comment]
Linking issue: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/450

**Comment by SimiHunjan** [comment]
Linking issue: https://github.com/hashgraph/hedera-mirror-node-explorer/issues/444

**Comment by SimiHunjan** [comment]
- Swagger document to formalize the APIs
- Testing requirements to not break the URLs

**Comment by Sheng-Long** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Project-Management-65318e909b304900162be143/issues/hashgraph/hedera-mirror-node-explorer/445?planning-poker) with Zenhub @Sheng-Long

**Comment by SimiHunjan** [comment]
Schedule time to review with the team

**Comment by ericleponner** [comment]
After reviewing various thread and issues (#338, #444, #450), here are URLs currently exposed by Explorer.

URLs from EIP 3091:
- `<BLOCK_EXPLORER_URL>`/block/`<BLOCK_HASH_OR_HEIGHT>`
- `<BLOCK_EXPLORER_URL>`/tx/`<TX_HASH>`
- `<BLOCK_EXPLORER_URL>`/address/`<ACCOUNT_ADDRESS>`
- `<BLOCK_EXPLORER_URL>`/token/`<TOKEN_ADDRESS>`

Additional URLs:
- `<HEDERA_EXPLORER_URL>`/`<NETWORK>`
- `<HEDERA_EXPLORER_URL>`/`<NETWORK>`/account/`<ACCOUNT_LOC>`
- `<HEDERA_EXPLORER_URL>`/`<NETWORK>`/contract/`<CONTRACT_LOC>`
- `<HEDERA_EXPLORER_URL>`/`<NETWORK>`/transaction/`<TRANSACTION_LOC>`

where:
- `<HEDERA_EXPLORER_URL> `= https://hashscan.io
- `<NETWORK>` = mainnet | testnet | previewnet
- `<BLOCK_EXPLORER>` = `<HEDERA_EXPLORER_URL>`/`<NETWORK>`
- `<ACCOUNT_LOC>` : account id | account address
- `<CONTRACT_LOC>` : contract id | contract address
- `<TRANSACTION_LOC>` :  consensus timestamp | transaction id | transaction hash | ethereum hash
- `<BLOCK_HASH_OR_HEIGHT>` : block hash or number
- `<TX_HASH>`: ethereum hash
- `<ACCOUNT_ADDRESS>` : account address
- `<TOKEN_ADDRESS>` : token address

**Comment by ericleponner** [comment]
To support URL: `<HEDERA_EXPLORER_URL>/<NETWORK>/contract/<CONTRACT_LOC>` we'll need to implement #432.
