### ISSUE TITLE
[high priority] Updates for MetaMask Compatibility 

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#454]
### Problem

When Hedera is used with MetaMask and includes the Hashscan block explorer URL(s), it doesn't function properly — we need to update Hashscan to work properly here.

### Solution

URL Redirects \| View Transaction  WORKS 👍 | https://hashscan.io/NETWORK/txn/00000000000.000000000   →  https://hashscan.io/NETWORK/transaction/00000000000.000000000
-- | --
URL Redirects \| View Account   **DOESN’T WORK 🚫** | https://hashscan.io/NETWORK/address/0x0000000000000000000000000  → https://hashscan.io/NETWORK/account/0x0000000000000000000000000
URL Redirects \| View Contract   **DOESN’T WORK 🚫** | https://hashscan.io/NETWORK/address/0x0000000000000000000000000   → https://hashscan.io/NETWORK/contract/0x0000000000000000000000000
**Description of what needs to happen for the above to work.** | When being directed from MetaMask to view a Contract or an Account entity, the link used for both of them is passed through from MetaMask as: **/NETWORK/address/0x000000000000000000000000**  HashScan needs to interpret this URL as a network-wide query for the entity that exists after /address/ and land the user on the appropriate **ACCOUNT** or **CONTRACT** page of HashScan for said entity.

### Alternatives

None

**Comment by ericleponner** [comment]
Following url:
[https://hashscan.io/mainnet/address/0x00000000000000000000000000000000001e0988](https://hashscan.io/mainnet/address/0x00000000000000000000000000000000001e0988)
displays details for account 0.0.1968520 aka 0x00000000000000000000000000000000001e0988.
I'm confused…

**Comment by bmgentile** [comment]
Hey @ericleponner — that only works because **.../address/0x00000000000** always redirects to an account

MetaMask uses a standard URL format of **.../address/0x00000000000** when clicking on an  **account** or a **contract** hyperlink to view details of either on an explorer.

If the user click on a hyperlink in MetaMask to view a contract, it will use the same format of **.../address/0x00000000000** and hashcan will attempt to redirect the user to an account with that EVM address, rather than a contract with that EVM address.

Does that make sense?

**Comment by ericleponner** [comment]
Ok, what you don't want is the two steps flow:
1) first display account details (using `{network}/address/{evm_address}`)
2) click on `Show associated contract` cross link (if any)

**Comment by bmgentile** [comment]
Correct! If the user is trying to view information about a specific contract, they should be directed to the contract info vs the account info related to the contract, upon landing.

**Comment by ericleponner** [comment]
@bmgentile I'm going to split this issue in two parts:
1) one part concerning the routing issue (ie landing on contract details when it's a contract)
2) another one concerning the visual changes.

**Comment by ericleponner** [comment]
I created #455  and copied visual change requests.

**Comment by bmgentile** [comment]
Okay thank you so much!
