### ISSUE TITLE
Improve display of evm addresses in account / contract and token details page

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node-explorer#455]
### Problem

This issue is a follow-up of #454 : it focuses on visual enhancements requested in #454.

### Solution

Requests from @bmgentile

Entity | Visual change
-- | --
Account View | (screenshot below) When viewing an account on HashScan, please continue to display the 0.0.XXXXX address at the very top (Account 0.0.XXXXX-fmnnu), AND to the right of that, display the Ethereum Alias address like this, in the same font size: EVM [copy/paste icon] 0xb2a….12ad
Token View | (screenshot below) When viewing a token on HashScan, please continue to display the 0.0.XXXXX address at the very top (Fungible Token 0.0.XXXXX-fmnnu), AND to the right of that, display the EVM address of the token like this, in the same font size: EVM [copy/paste icon] 0x000….539ee  \|  $SYMBOL
Contract View | (screenshot below) When viewing a contract on HashScan, please continue to display the 0.0.XXXXX address at the very top (Contract 0.0.XXXXX-fmnnu), AND to the right of that, display the EVM address of the contract like this, in the same font size: EVM [copy/paste icon] 0x000….539ee \| Show associated account

**************Account, Token, & Contract View**************

![image](https://user-images.githubusercontent.com/3035858/219971380-cb5813fb-d5fb-4779-9686-288057ab6d4a.png)

![image](https://user-images.githubusercontent.com/3035858/219971412-6676dc9c-f14b-4ca2-8c1e-e70f1e4ef3ec.png)

![image](https://user-images.githubusercontent.com/3035858/219971423-a11471cf-d4d0-457a-baa4-a77dc5a0a4ab.png)

**Comment by svienot** [comment]
Suggest to do something similar to this for _contract, account & token_:

<img width="1024" alt="Screenshot 2023-02-20 at 22 58 20" src="https://user-images.githubusercontent.com/16097111/220204813-34c602fb-237f-4306-aa37-41f8d643a857.png">

@bmgentile your feedback is welcome.

**Comment by bmgentile** [comment]
That looks good but maybe in white font & a copy/paste icon to the left of it for users to easily cop/paste the address.

And labeling it as "**EVM Address**" before the address.

**Comment by bmgentile** [comment]
Something like the below is super clean:

**Contract**
Entity ID 0.0.XXXXX
EVM Address [copy/paste icon] 0x000000

**Comment by svienot** [comment]
@bmgentile we have deployed a prototype of your suggestion on staging server.

**Comment by bmgentile** [comment]
@svienot — could I get access to the staging server to check this out?

**Comment by bmgentile** [comment]
Hey @svienot — just checked out staging for Contracts, Accounts, & Tokens; this looks perfect! Appreciate the changes and this is good to ship.
