### ISSUE TITLE
Support EthereumTransaction type

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node-explorer#46]
### Problem

The new `EthereumTransaction` type is picked up in the Crypto transfer section but not the `Smart Contract Calls` section of the dashboard.

### Solution

Add recognition for cases where `EthereumTransaction` calls a SmartContract
- calls a smart contract
- both sends HBAR/tokens and calls a smart contract

**Comment by svienot** [comment]
Could you point us to the schema of the REST API for this new transaction (or a sample JSON value), because we are not sure how to handle it at this point?

**Comment by Nana-EC** [comment]
> Could you point us to the schema of the REST API for this new transaction (or a sample JSON value), because we are not sure how to handle it at this point?

It hasn't been exposed via rest API - not sure that it will be as is.
Users would use existing `/api/v1/transactions` and `/api/v1/contracts/results` endpoints to retrieve information.
So there shouldn't be anything new if you already fully support the responses from those endpoints.
What you will be able to see is that the transactionType from a call to `/api/v1/transactions...` will be `EthereumTransaction`

**Comment by svienot** [comment]
You can see the Hashscan tables as (most of the time) the result of a single query to the REST API.
So, for instance on the [home dashboard page](https://hashscan.io/#/mainnet/dashboard), the table "**Crypto Transfers**" is built on a call like: `/api/v1/transactions?transactiontype=CRYPTOTRANSFER` and the table "**Smart Contract Calls**" is built on something like: `/api/v1/transactions?transactiontype=CONTRACTCALL`

So, in order for an EthereumTransaction to show up in this tables, we would need the REST API to return it as part of the queries above. 

If `ETHEREUMTRANSACTION` is just a new type added to `TransactionType`, such transactions will show up in the [Transactions page](https://hashscan.io/#/mainnet/transactions), either when selecting `TYPES: ALL`, or when specifically selecting the type `ETHEREUMTRANSACTION`.

**Comment by Nana-EC** [comment]
I see.
If the tables are supposed to be a 1:1 map of the `transactiontype` then there's no operation here to modify each table. Instead in the future you may considering adding an `EthrereumTransaction` table using  `transactiontype=EthrereumTransaction` and accommodate displaying both transfer and contract info accordingly.
Probably the cleaner option so there's no transaction repetition.

The [Transactions page](https://hashscan.io/#/mainnet/transactions) works fine. `EthrereumTransaction` just needs to be added to that drop down
