### ISSUE TITLE
Fungible Tokens should be displayed with a decimal point

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-mirror-node-explorer#47]
### Problem

Fungible tokens have a defined number of places past the decimal, yet in HashScan the decimal doesn't show.

### Solution

Add the decimal to all places where the fungible token amount is.

![image](https://user-images.githubusercontent.com/3486721/167227504-166d3953-df30-4092-be30-6915df19629d.png)

**Comment by staplrbus** [comment]
This is important for general usability
