### ISSUE TITLE
Hashscan.io Staking Reward Filter

### ISSUE THREAD

**Issue by michaelowen37** [hashgraph/hedera-mirror-node-explorer#488]
### Problem

Tracking and reporting staking rewards for tax or planning purposes.  Currently, on Hashscan.io, the staking rewards on the bottom of the screen (when viewing an account) are split between multiple pages.  If you wanted to see how much you have accumulated in a week, month, or year, it requires pulling out a calculator and navigating several pages of reward distributions (which can run together after awhile).   

### Solution

Adding a filter option such as:

Rewards in 2023
Rewards in 2022
Previous Month
Previous Week
Previous Six Months 
Custom Range

### Alternatives

Integrations with tax reporting software such as TurboTax or H&R block.  Exportable .pdf or spreadsheet.

**Comment by ericleponner** [comment]
In the `Staking` tab, there is action to download staking rewards as a CSV file.

1) Select `Staking` tab in top navigation bar
2) Connect to your wallet
3) In `Recent Staking Rewards` section (top right), click download button

**Comment by michaelowen37** [comment]
Thank you for the response!  Sounds like user error, my apologies.
