### ISSUE TITLE
Hashscan Total Supply display is totally incorrect (mainnet)

### ISSUE THREAD

**Issue by Topachi** [hashgraph/hedera-mirror-node-explorer#495]
### Description

if you go to check HSUITE token info here https://hashscan.io/mainnet/token/0.0.786931 you will see that total supply displayed is 0.9229, which is totally incorrect, as there are billions in total supply.

### Steps to reproduce

1. Go to https://hashscan.io/mainnet/token/0.0.786931
2. Check the current total supply

### Additional context

The total supply should be the total supply minted - any burnt/wiped tokens.

### Hedera network

mainnet

### Version

latest

### Operating system

macOS

**Comment by xin-hedera** [comment]
mirrornode ticket here: https://github.com/hashgraph/hedera-mirror-node/issues/5642
