### ISSUE TITLE
Wallet connection should be accessible globally 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#498]
### Problem

Currently, the wallet connection is within the flow of staking. To connect to the wallet, you have to visit the staking page. If there is support for the user to sign additional transaction types, it becomes confusing as the user has to visit the staking page to connect to their wallet to sign other types of transactions.

The two transactions that connect to wallet today are the account update transaction for staking and the approval and allowance transactions. 

### Solution

Design a solution where the wallet can be more globally applied to sign more than just the staking transaction. 

- [ ] Design the solution
- [ ] Get feedback
- [ ] Deploy to staging
- [ ] Release

**Comment by Neurone** [comment]
I suggest:

- Creating a recurrent UI element (i.e., a dedicated icon) that identifies when the user's following action is going to trigger a request for a signature
- Creating a dedicated page for user preferences. There I can check, among other things, the status of my wallet connection.

**Comment by SimiHunjan** [comment]
Design have been approved for the global wallet access
