### ISSUE TITLE
Allow to view and delete existing NFT allowances

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node-explorer#520]
### Problem

The Mirror Node Explorer currently allows to approve allowances for NFTs (selected serial numbers, or the whole class) but does not allow to visualise existing such allowances, and does not allow to delete them.
(Follow-up to the requirement expressed in #499)

**User Stories**

- As a developer or retail user, I want to see what contracts or accounts can spend NFTs on behalf of my account.
- As a developer or retail user, I want to remove a contract or account allowance for NFTs.

### Solution

- Add another table to the Account view, to visualize existing NFT Allowance.
- Similar to what is done for modifying hbar/fungible token allowances, provide a way to delete an existing allowance from that table.

**Comment by svienot** [comment]
This requires the endpoint `/api/v1/accounts/{idOrAliasOrEvmAddress}/allowances/nfts` to be added to REST API, as described in [HIP-336](https://hips.hedera.com/hip/hip-336) and tracked by issue[ #3245](https://github.com/hashgraph/hedera-mirror-node/issues/3245)

**Comment by SimiHunjan** [comment]
Mirror Node HIP for rest API: https://github.com/hashgraph/hedera-improvement-proposal/pull/857/files

**Comment by SimiHunjan** [comment]
Mirror node issue: https://github.com/hashgraph/hedera-mirror-node/issues/7480
