### ISSUE TITLE
Inactive Address | All EVM Combinations

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#536]
### Problem

When someone is using MetaMask with an existing EVM address and adds the Hedera network, they may try to go check HashScan for that EVM address prior to sending HBAR to it for a "lazy account creation".

On Etherscan, the user can look up any address that hasn't yet been used and they're presented with something like this, which still displays **_some_** information about the account: https://etherscan.io/address/0x26C164c21B5C5E347c1B97e4A8Ea7b19FA8c89D3

The problem on Hedera is that they will see an error message "page not found" for the EVM address they're searching on HashScan and potentially be confused about the viability of using that account with the Hedera network.

**Possible URLs / paths they'll use to get there:**
Directly from MetaMask: https://hashscan.io/mainnet/address/0xABa701270045F0269603cC4850242AFEeFc65F67

When manually searching for the EVM address is displays a "No result" page.

<pimg width="1728" alt="image" src="https://user-images.githubusercontent.com/3035858/230547216-ab122c15-31e6-4e27-9f87-9a8b1a4010c5.png">

### Solution

**When the following URLs / paths for an inactive EVM address are requested:**
https://hashscan.io/mainnet/account/0x###########
https://hashscan.io/mainnet/address/0x###########
And when searching for an inactive EVM address in the HashScan search box.

**The user should see a page that looks exactly like the screenshot attached**
• **Inactive address**
• Account ID: Assigned upon activation
• _blue or green banner_ Own this account? Activate it by transferring any amount of ℏ or tokens to 0x…######.
• Balance: 0.00000000ℏ $0.0000
• "Not yet enabled" for "Auto Renew Period" 
• "None" for all other fields

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/3035858/230550632-890e95d1-18a3-4545-b0c9-e539d9f35ace.png">

**Comment by ericleponner** [comment]
From HashScan standpoint:
https://hashscan.io/mainnet/0x26C164c21B5C5E347c1B97e4A8Ea7b19FA8c89D3
is considered as a badly constructed URL hence the page not found response.
Valid URL (from EIP 3091) is:
https://hashscan.io/mainnet/address/0x26C164c21B5C5E347c1B97e4A8Ea7b19FA8c89D3
And response is:
![image_720](https://user-images.githubusercontent.com/91124272/230556951-3a1152a4-e007-4e2a-84b2-e41de3ae63b6.png)

**Comment by bmgentile** [comment]
Gotcha that makes sense; thank you for clarification on that. I think we'll still want changes to the page for "address not found" to reflect the proposed solution to ensure a solid user experience.

**Comment by ericleponner** [comment]
Word "address" is not part of HashScan vocabulary so far.  From a UX standpoint, we need to be careful before introducing it and avoid to confuse users that have understood Hedera model.
Since we in the context of an auto-created account (right?) and the {network}/address/{ethAddress}, we may have a specific page that teach the user and make the link between address (ie Ethereum world) and account (ie Hedera world).
Let us think about that and come back with a proposal.

**Comment by bmgentile** [comment]
Thanks for the info, @ericleponner! Your insight on "address" is helpful. For reference, the page you're referring to is in the Hedera docs here, which explains "auto account creation": https://docs.hedera.com/hedera/core-concepts/accounts/auto-account-creation

Since an EVM address can potentially be an "account", "token", "contract", or "transaction", I think it makes sense to use the term "Address" here for technical accuracy. 

How about a compromise: we could call it **Inactive EVM Address**, which is a term that we do use?

As for the user experience, we anticipate users will be going **directly from MetaMask** to HashScan to view their account (see the screenshot below). Where they land when doing this should be designed in such a way that users can quickly and intuitively understand the situation without having to click through or hover on anything. 

The re-designed view for an "Inactive EVM Address" supports this, but agreed it might be a good idea to include a link to the doc page above for more details, just in case.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/3035858/230747270-1e1e7004-38ff-42a8-aea2-8d5874c519f5.png">
