### ISSUE TITLE
Node owners are incorrect for testnet and previewnet

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node-explorer#54]
### Description

Check a transaction including hbar transfers on testne or previewnett, the map of payments to nodes under "Hbar Transfers" list node owners from the mainnet list, on testnet and previewnet, nodes are not hosted by council members.

e.g. https://hashscan.io/#/testnet/transaction/0.0.11093-1652180465-382616732?t=1652180476.585125656

should not show `Node 0 - LG - Seoul, South Korea` for account `0.0.3`

### Steps to reproduce

navigate to https://hashscan.io/#/testnet/transaction/0.0.11093-1652180465-382616732?t=1652180476.585125656

Hbar transfers map should not show `Node 0 - LG - Seoul, South Korea` for account `0.0.3`, the node description is incorrect for testnet and previewnet.

### Hedera network

testnet
previewnet

### Version

n/a

**Comment by ericleponner** [comment]
Does it still make sense to label 0.0.98 with « Hedera fee collection account » in that context ?
