### ISSUE TITLE
Token Symbol for Child Transactions

### ISSUE THREAD

**Issue by bmgentile** [hashgraph/hedera-mirror-node-explorer#540]
### Problem

When I view HashScan for transactions in DeFi, it's typically a single transaction that includes a number of child transactions related to the transfer of tokens.

Upon viewing the origin transaction, I don't want to have to click into each of the child transactions in order to understand which one it is that contains the Crypto Transfer of the specific token I'm looking for — I'd like to know before having to click into all of them. Please see screenshot below.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/3035858/231020414-72827b8b-b8c8-4a0a-89b3-a508138a5ae1.png">

### Solution

To provide me with additoinal context and not have to do "guess, click, check" it'd be great to show the token symbols next to:  Token Mint, Token Burn, Token Delete, Token Update, Token Create, Token Pause, Token Unpause, Token Associate, and Crypto Transfer

So something that look like this (or similar) would be awesome:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/3035858/231021332-ed8bfca3-735a-4e3d-be06-386612f31dac.png">

**Comment by ericleponner** [comment]
Note that you may click `Show all transactions with same ID` link:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/91124272/231135920-c6e6e1fa-b684-4b1a-94e9-fabbadd97c03.png">

and get the full list of children in a tabular way:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/91124272/231136082-1f61f979-f4f3-4334-94c6-9fd0f22414a8.png">

`Child Transactions` field is a kind of shortcut when there are few values. 
The real tool to explore the `Transaction with ID` table.

**Comment by SimiHunjan** [comment]
@bmgentile do you have any feedback on the above?

**Comment by bmgentile** [comment]
@SimiHunjan @ericleponner I think having these at a glance would be valuable for folks (the screenshot); it's way more intuitive.

**Comment by ericleponner** [comment]
@bmgentile So you want a "Child Transactions" table inlined in the Transaction Details page, right.
In the example above, that table would contain the two last lines.

**Comment by bmgentile** [comment]
@ericleponner i think I'm understanding what you're saying -- the child transactions view that currently exists on the transaction details page would just include small text string in light blue of the token symbol, to the right of child transactions related to a specific token, allowing the user to see, at a glance, which token is related to whatever token-related child transaction is listed.

**Comment by bmgentile** [comment]
Hey @ericleponner any updates on this?

**Comment by ericleponner** [comment]
Nothing planned for the moment.
