### ISSUE TITLE
Incorrect fee for CryptoUpdate transaction

### ISSUE THREAD

**Issue by michielmulders** [hashgraph/hedera-mirror-node-explorer#562]
### Description

The transaction fee for an account update is $0.00022 according to our [docs](https://docs.hedera.com/hedera/networks/mainnet/fees) and the [`services code`](https://github.com/hashgraph/hedera-services/blob/4bc8951c0c38da0f8a9db19e2ba41026585320b0/hedera-node/hapi-fees/src/main/resources/canonical-prices.json).

At the moment, Hashscan shows $0.0002. Is the last digit truncated?

### Steps to reproduce

Here's an example transaction on the [mirror node](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.604193-1682373946-438550950/) and [Hashscan](https://hashscan.io/mainnet/transaction/1682373957.837107003).

### Hedera network

mainnet

### Version

latest

### Operating system

macOS

**Comment by ericleponner** [comment]
Dollar amount is currently rounded to 4 digits.
We could add more digits if needed.
What would you recommend ?

**Comment by michielmulders** [comment]
@ericleponner I would recommend 5 digits because it's confusing to the end user if they actually paid the 0.00022 fee or not.
