### ISSUE TITLE
Long memo stretches outside of panel

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node-explorer#566]
### Description

Displaying a token with a long memo, the memo is seen to stretch beyond the left hand panel instead of wrapping (or other expand/collapse).

for example: https://hashscan.io/testnet/token/0.0.3947766?p=1&k=0.0.3947765

### Steps to reproduce

See here: https://hashscan.io/testnet/token/0.0.3947766?p=1&k=0.0.3947765

### Hedera network

testnet

### Version

unkonwn

### Operating system

None

**Comment by svienot** [comment]
We can make sure that the _memo_ wraps like this:
<img width="620" alt="Screenshot 2023-05-10 at 15 32 14" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/1a7adb36-5a15-4c6e-aac4-9cee5c8840a6">

But we could also, when it happens to contain a json value like in this case, display this:
<img width="620" alt="Screenshot 2023-05-10 at 15 31 31" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/a954ff0f-b23b-46fb-a441-75e01cb95c40">

Any preference @gregscullard ?
