### ISSUE TITLE
spender allowance does not decrease as allowance is spent

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#567]
### Description

If an Alice's account approves Bob's account with an allowance of 100 TokenX then if Bob spends `x` amount where `x <= 100` then Bob's allowance should decrease by `x`.

Take [0.0.1055570 account](https://hashscan.io/mainnet/account/0.0.1055570) as an example which approved [account 0.0.2178425](https://hashscan.io/mainnet/account/0.0.2178425) 100 [WHBAR](https://hashscan.io/mainnet/token/0.0.2178426).

The spender spent the entire 100 WHBAR allowance in [this transaction](https://hashscan.io/mainnet/transaction/1682510657.531240004) where it transferred the 100 WHBAR to itself. However it's `amount_granted` did not decrease to `0`.

```shell
curl -X 'GET' \
  'https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.1055570/allowances/tokens?limit=2&order=desc&spender.id=0.0.2178425&token.id=0.0.2178426' \
  -H 'accept: application/json'
```

```json
{
  "allowances": [
    {
      "owner": "0.0.1055570",
      "spender": "0.0.2178425",
      "timestamp": {
        "from": "1682510616.672953003",
        "to": null
      },
      "amount_granted": 10000000000,
      "token_id": "0.0.2178426"
    }
  ],
  "links": {
    "next": null
  }
}
```

### Steps to reproduce

The description more or less outlines how this can be reproduced.

I can give a simple demo example if required.

### Hedera network

mainnet

### Version

0.78.1

### Operating system

None

**Comment by ericleponner** [comment]
This issue concerns a core feature of Hedera network.
I would be more efficient to directly file it in [hashgraph/hedera-services](https://github.com/hashgraph/hedera-services).
