### ISSUE TITLE
Wrong Token Supply Display on Token Page

### ISSUE THREAD

**Issue by defigirlxo** [hashgraph/hedera-mirror-node-explorer#572]
### Description

**Problem**
The HashScan UI displays a wrong balance for token supplies of integers containing more than 16 digits.
On the _token_ and _balance_  pages of HashScan [(example here)](https://hashscan.io/mainnet/token/0.0.284338), the total supply displayed is:
9,223,372,036,854,776,000

which is wrong as it is being rounded up from the actual supply which is:
9,223,372,036,854,775,807

### Steps to reproduce

[Visit this token page](https://hashscan.io/mainnet/token/0.0.284338?p=1&k=0.0.278981)

### Additional context

[This Create a Token Documentation](https://docs.hedera.com/hedera/sdks-and-apis/sdks/readme-1/define-a-token) specifies the initial supply of fungible tokens to be put in circulation. The initial supply is sent to the Treasury Account. The maximum supply of tokens is 9,223,372,036,854,775,807(2^63-1) tokens and is in the lowest denomination possible. For creating an NFT, you must set the initial supply to 0.

### Hedera network

mainnet

### Version

v0.1.0

### Operating system

macOS

**Comment by svienot** [comment]
[mirror-node returns](https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.284338) the correct values as strings, e.g:
  "initial_supply": "9223372036854775807",
which HashScan converts into Number hence the rounding. It should use BigInt instead.

However I notice that when getting the token balances, [mirror-node returns the balance](https://mainnet-public.mirrornode.hedera.com/api/v1/tokens/0.0.284338/balances) as an integer, not a string, and we get this:
"balance": 9223372036854776000

@steven-sheehy I was wondering why this is so? I am not sure how we can display the correct balance if we do not get it as a string?
