### ISSUE TITLE
Incorrect token amounts displayed

### ISSUE THREAD

**Issue by tom-hbar** [hashgraph/hedera-mirror-node-explorer#581]
### Description

Incorrect token amount values are being displayed when viewing account balances, token transfers and token supply. While the decimal is displayed, it appears the amount is not being divided by the number of decimals the token has.

For example, on the [USDC token page](https://hashscan.io/mainnet/token/0.0.456858) it displays the total supply as 250,010,000,000,000.000000 when the correct total supply is 250,010,000.000000

[This account](https://hashscan.io/mainnet/account/0.0.849381) shows a balance of 4,737,989,025,714,397.00000000 HBARX when the correct balance is actually 47,379,890.25714397

### Steps to reproduce

1. Go to any page on hashscan that displays token amounts (balances, transfers, supply values)

### Hedera network

mainnet

### Version

?

### Operating system

macOS

**Comment by ericleponner** [comment]
Looks like a side effect of fix for #572.
We'll look at that asap.
Thanks for reporting @tom-hbar.
