### ISSUE TITLE
Explorer fails to decode call to system contract

### ISSUE THREAD

**Issue by ericleponner** [hashgraph/hedera-mirror-node-explorer#600]
### Description

Explorer fails to decode the following call to system contract:

https://hashscan.io/mainnet/transaction/1684236107.179110285

<img width="1007" alt="image" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/91124272/de7323e9-bf9f-4bff-8ead-1fc928d8f25f">

In navigator console, the following error is reported by parseTransaction() function (ethers library):

```
Uncaught (in promise) Error: no matching function (argument="sighash", value="0x618dc65e", code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (index.js?ffb2:224:1)
    at Logger.throwError (index.js?ffb2:233:1)
    at Logger.throwArgumentError (index.js?ffb2:236:1)
    at Interface.getFunction (interface.js?a807:143:1)
    at Interface.parseTransaction (interface.js?a807:548:1)
    at _callee$ (FunctionCallAnalyzer.ts?d126:119:1)
    at tryCatch (runtime.js?96cf:63:1)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294:1)
    at Generator.eval [as next] (runtime.js?96cf:119:1)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3:1)
```

### Steps to reproduce

Go to https://hashscan.io/mainnet/transaction/1684236107.179110285

### Hedera network

mainnet

### Version

Built Mon, 15 May 2023 14:06:52 GMT

### Operating system

macOS

**Comment by ericleponner** [comment]
Root cause of decoding error is that HTS ABI embedded in Explorer (`IHederaTokenService.json`)  is obsolete.

However using the [latest ABI](https://github.com/hashgraph/hedera-smart-contracts/blob/main/artifacts/contracts/hts-precompile/IHederaTokenService.sol/IHederaTokenService.json), `etherjs` still throws a `data out-of-bounds` error.
So it looks like `input` value from [1684236107.179110285](https://hashscan.io/mainnet/transaction/1684236107.179110285) cannot be decoded anymore.

Anyway Explorer should be enhanced and inform user that it is facing an invaliding encoding.

**Comment by mshakeg** [comment]
Hi @ericleponner can you elaborate why the call cannot be decoded even using the latest HTS abi?

I've experienced this issue very recently: https://hashscan.io/testnet/transaction/1687896276.413382005

**Comment by ericleponner** [comment]
Hi @mshakeg
You can find more information in the [bug](https://github.com/hashgraph/hedera-smart-contracts/issues/237#issuecomment-1614611882) I filed in smart-contract.
However my conclusions might be wrong according latest bug update. I need to dig into it a bit more i guess.
