### ISSUE TITLE
Can't see InitCode and Recent Transactions of Contract in Hedera Mirror Node Explorer

### ISSUE THREAD

**Issue by chlrbtlr30** [hashgraph/hedera-mirror-node-explorer#603]
### Description

After deploying toy smart-contract to Local Network, I can't see initcode and Recent Transactions.
(But smart contract calls work well as intended.)

This is same for TESTNET at Hedera Mirror Node Explorer.

I don't know why.

Any help?

### Steps to reproduce

1. Deploy contract to local network
2. call smart contract transaction

### Additional context

![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/25427482/12c620fa-a388-4a82-bcd8-4f1da7b4565b)
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/25427482/9f97b729-8878-4036-81d0-13c165bd84c9)

### Hedera network

other

### Version

latest

### Operating system

Linux

**Comment by svienot** [comment]
If the explorer shows an empty initcode, this is normally because the underlying mirror-node REST call returned it empty.
Could you please confirm by calling the endpoint `api/v1/contracts/0.0.1032` on your development mirror-node and checking the value of the returned `bytecode` field?

**Comment by chlrbtlr30** [comment]
Figured out.
The version in the docker registry is 2 months old, which is probably too old. Using the latest explorer from the main branch solved the problem. Can you update the version of explorer in the docker registry?
<img width="953" alt="스크린샷 2023-05-18 오후 6 28 37" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/25427482/fa93ff6e-1f50-4677-983a-aa952eff9272">

**Comment by svienot** [comment]
Just pushed the latest image.
