### ISSUE TITLE
HashScan should show the transaction hash in a usable form (Hedera 48-bytes & EVM 32-bytes)

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-mirror-node-explorer#623]
### Problem

Consider this transaction:
- https://hashscan.io/mainnet/transaction/1685742901.591716003
- https://hashscan.io/mainnet/tx/0x1000f86d0ea7169069022d573db69d8b20b586bbab93dd0161efb2c4f74c0c3f
- https://mainnet-public.mirrornode.hedera.com/api/v1/contracts/results/0x1000f86d0ea7169069022d573db69d8b20b586bbab93dd0161efb2c4f74c0c3f

HashScan shows the Transaction Hash as:
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/72571340/1fa3d8b9-f1de-4996-8fc3-0664b74a4222)

This is because Hedera tx hashes are 48 bytes. However, EVM tx hashes are 32 bytes (as explained in [this StackOverflow answer](https://stackoverflow.com/questions/76228588/how-can-i-use-a-transaction-hash-from-hashscan-in-a-json-rpc-query-on-hedera
)). 

**This 48-byte form of the hash, however, is not really usable by any other tool (EVM tools, Mirror REST API, or even HashScan itself - see all links above - they use the 32-byte hash).** 
We should make it easy for developers and non-developers to obtain the tx id AND a usable tx hash from HashScan - the change proposed below would support that. 

### Solution

Please consider: 
**- Renaming the existing field to `Hedera Transaction Hash` AND adding a field right below called `EVM Transaction Hash`**

`Hedera Transaction Hash`: 
0x1000f86d0ea7169069022d573db69d8b20b586bbab93dd0161efb2c4f74c0c3f132654d46f17cacc4b240d02022146cb
`EVM Transaction Hash`: 
0x1000f86d0ea7169069022d573db69d8b20b586bbab93dd0161efb2c4f74c0c3f

As we onboard new developers, wallets, exchanges, and retail users, we should make it easy to find equivalent information between tools.

**Comment by bguiz** [comment]
Related: https://stackoverflow.com/q/76228588/194982
