### ISSUE TITLE
Improve understanding of "Nonce" and "Ethereum Nonce" fields

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-mirror-node-explorer#626]
### Problem

When visiting details of transactions you can notice the "Nonce" field. That field is used for different things, but it's different from the Ethereum Nonce.

When the tx is an Ethereum transaction (i.e., https://hashscan.io/testnet/transaction/1684483329.103151936), the "Nonce" field can easily be misinterpreted as the "Ethereum nonce" that you can correctly see only visiting the contract's results (i.e., https://testnet.mirrornode.hedera.com/api/v1/contracts/0.0.4616849/results/1684483329.103151936).

### Solution

- Rename "Nonce" field into "Transaction Nonce"
- Add "Ethereum Nonce" to the transaction details if the transaction is an Ethereum Transaction
- Add tooltips to explain the difference between the two nonces

**Comment by Neurone** [comment]
> IMO it should be `Transaction Nonce`. And we shouldn't purely speak in terms of children and parents as there could be nonce greater than 0 that are not related to the nonce=0 transaction.

Agree. Updated the issue.

**Comment by Nana-EC** [comment]
Agreed on "Rename "Nonce" field into "Transaction Nonce"" and on adding "Ethereum Nonce" to the "Contract Result" section

**Comment by svienot** [comment]
Currently deployed on staging server.
Looks like this:
<img width="1089" alt="Screenshot 2023-06-07 at 20 39 34" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/a5175080-61a5-4bad-ad73-56ed0c8ca19c">
