### ISSUE TITLE
Contract error returns should be decoded if they are ASCII

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-mirror-node-explorer#646]
### Problem

Consider for example https://hashscan.io/previewnet/transaction/1686939577.451858743 and note the error return:

![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/117694041/5b71f1a8-748d-44f8-b16d-63d1383bdbfb)

The returned error blob - `544f4b454e5f4e4f545f4153534f4349415445445f544f5f4143434f554e54` - is not decoded, but drop it into a [hex-&gt;ascii converter](https://www.rapidtables.com/convert/number/hex-to-ascii.html) and you see it really is `TOKEN_NOT_ASSOCIATED_TO_ACCOUNT`.  Which is really interesting to know.

### Solution

If current decoding methods (table lookup?) don't produce a result try interpreting the buffer as ASCII - if it's valid and sane ASCII use that, otherwise only then fallback to a "dunno what's here" message.

* valid ascii: high-bit off
* sane ascii: only characters in `\w+` (maybe adding space and a few punctuation characters like `!`, `?`)

### Alternatives

Manually dropping the hex string each time into https://www.rapidtables.com/convert/number/hex-to-ascii.html.  Which is a bit inconvenient on its own but also the "copy" feature copies the leading `0x` which it arguably shouldn't, and that particular online converter isn't smart enough to remove it.  Sigh.

**Comment by ericleponner** [comment]
Right now, Explorer makes a string decoding only if error message starts with 0x08c379a0.
It looks like there are some cases where we have a string without this prefix.
Are you aware of any spec which describes how error message is encoded ?

**Comment by ericleponner** [comment]
Screenshot above also exhibits a bug: `Output Result` field is `None` so message `Decoding Error(overflow)` is irrelevant and should not be displayed.
