### ISSUE TITLE
Hyperlink for token id in contract call trace thinks it's a contract - should redirect to the actual token 

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hedera-mirror-node-explorer#651]
## Context
HTS System Contracts can be called directly (without the need to deploy an intermediary contract) by treating the `tokenAddress` as the `contractAddress`. 
Basically, this JS code using Ethers JS works (treating tokenAddress as if it were contractAddress): 
```
CREATE CONTRACT INSTANCE FOR THE TOKEN ADDRESS
const myContract = new ethers.Contract(tokenAddress, abi, signer);
const associateTx = await myContract.associate({ gasLimit: gasLimit });
const associateRx = await associateTx.wait();
```
## The Problem
See the **Call Trace** section for transaction in HashScan:
https://hashscan.io/previewnet/tx/0xa34851b8f0df391c38a73230265e5118741408ab982c5f64345db35cee22e360

![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/72571340/5859b3a0-3825-4741-b629-d7180d0dba7a)

The call trace shows: **User account => token address => HTS System Contract**

When clicking on the **token id hyperlink** shown in the call trace, HashScan treats that ID as if it were a contract, which is problematic because:
❌ https://hashscan.io/previewnet/contract/0.0.230049
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/72571340/cd4cf5f4-e1a5-4127-a6c8-ebcb02c9ac0a)

Instead, that hyperlink should redirect to the token with that entity id:
✅ https://hashscan.io/previewnet/token/0.0.230049
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/72571340/859d991b-dad0-486b-816d-69a981b96d47)

### Steps to reproduce

See description and hyperlinks above.

### Hedera network

mainnet, testnet, previewnet

### Version

v0.82.1

### Operating system

Windows

**Comment by svienot** [comment]
The transaction details of the related ETHEREUM TRANSACTION also wrongly display the target entity as an Account:

<img width="1114" alt="Screenshot 2023-06-27 at 10 14 45" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/40db6b92-61ce-4743-9a45-61931bd04e6a">

**Comment by svienot** [comment]
@steven-sheehy would it be conceivable for mirror-node to return the `caller_type`/`recipient_type` fields in `ContractActionsResponse` as an enum: `[ ACCOUNT, CONTRACT, TOKEN ]` instead of `[ ACCOUNT, CONTRACT]`
As it stands, we are simply going to call the API each time we get the value CONTRACT to check whether it is indeed a contract or in fact a token.
