### ISSUE TITLE
Add HIP-646/765: Fungible/non-Fungible Token Metadata Field

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#671]
### Problem

HIP-646 introduces new Hedera protobuf changes where the a token metadata field is added to the `TokenCreateTransaction` and `TokenUpdateTransaction.` This metadata field will also be returned in the `TokenInfoQuery`. The same changes are mentioned in HIP-765 for non-fungible tokens.

**HIP**

- [x] https://hips.hedera.com/hip/hip-646
- [x] https://hips.hedera.com/hip/hip-765

**Hedera Protobuf**

- [ ] https://github.com/hashgraph/hedera-protobufs/pull/313/files
- [ ] https://github.com/hashgraph/hedera-protobufs/pull/322/files

**Hedera Services Release**
 - 0.48

 **Mirror Node Release**
- 0.100.0
- https://github.com/hashgraph/hedera-mirror-node/issues/7596

### Solution

- [ ] UI Design
- [ ] Feedback
- [ ] Staging
- [ ] Review
- [ ] Release

**Comment by svienot** [comment]
The issue to watch from explorer standpoint is https://github.com/hashgraph/hedera-mirror-node/issues/6549.
