### ISSUE TITLE
Add HIP-782: Smoothing Staking Rewards

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#679]
### Problem

HIP-782 describes modifying the staking reward rate property.

HIP: https://hips.hedera.com/hip/hip-782

HIP: https://github.com/hashgraph/hedera-improvement-proposal/pull/786/files

Mirror Node:
- issue to track TBD

### Solution

Review the changes and modify UI where applicable.

**Comment by svienot** [comment]
Suggesting to do these changes: 
<img width="1265" alt="Screenshot 2023-11-30 at 23 59 17" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/457aa883-5e7f-403d-a2b7-441dc2101198">

Also visible on the staging server.
