### ISSUE TITLE
Show correct `gasPrice` for ethereum transactions

### ISSUE THREAD

**Issue by AlfredoG87** [hashgraph/hedera-mirror-node-explorer#693]
### Problem

Currently for `Ethereum Transactions` the explorer is not showing the `gasPrice`.

<img width="1480" alt="image" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/123040664/c3290e58-b1ef-4bcd-bd4b-006b866f56a7">

And when calling `mirror-node` 

```
https://previewnet.mirrornode.hedera.com/api/v1/contracts/results/0xa8795e383e7ee5b138e61f5da7b0d85664e6feec3f2e5e24385f2ff265c401d3?nonce=1
```

as part of the results, there is the following related fields:

"gas_price": "0x",
"max_fee_per_gas": "0x55",
"max_priority_fee_per_gas": "0x0",

According to my understanding the `gas_price` is used for type `0` transactions (legacy)
`max_fee_per_gas` for type `2` transactions and `max_priority_fee_per_gas` for type `1` transactions. 

<img width="297" alt="image" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/123040664/54ce7c69-0963-425b-bc0e-d2dde1a57794">

### Solution

Use the appropiate field to populate the gasPrice on the explorer.

**Comment by ericleponner** [comment]
Displayed data are correct. This was a misunderstanding of @AlfredoG87. Closing.
