### ISSUE TITLE
Incorrect memo display.

### ISSUE THREAD

**Issue by moshenskyDV** [hashgraph/hedera-mirror-node-explorer#694]
### Description

Got some small visual bug on hashscan. Account memo specificly for phrase "adap" displayed as strange symbol. Worth to mention that it's only word that cause this bug for me. Any other word works well.
Test account with reproduced issue: https://hashscan.io/testnet/account/0.0.1709113
Also screenshot attached.
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/15670713/bcc6f6ca-a32d-4611-a206-458248cc3240)

### Steps to reproduce

1. Create new account with `.setAccountMemo('adap')`
2. Check visual of memo on Hashscan.

### Hedera network

mainnet, testnet, previewnet

### Version

latest

### Operating system

None

**Comment by quiet-node** [comment]
Hello, @moshenskyDV! Thanks for raising the issue. Could you please provide me with some more HashScan links to other cases where the `memo` displays correctly as you've set it using `.setAccountMemo()`?

**Comment by moshenskyDV** [comment]
Correct displaying:
https://hashscan.io/testnet/account/0.0.2008265
`.setAccountMemo('anothermemo')`

BTW: tried to hit around incorrect one - and looks like I'm able to another incorrects.
https://hashscan.io/testnet/account/0.0.2008284
`.setAccountMemo('adao')`
https://hashscan.io/testnet/account/0.0.2008313
`.setAccountMemo('adat')`

**Comment by moshenskyDV** [comment]
@quiet-node I did a couple of more tests and found that incorrect memo appears only from 4 symbol word.
Here is other examples:
https://hashscan.io/testnet/account/0.0.2008403
`.setAccountMemo('aca1')`

https://hashscan.io/testnet/account/0.0.2008437
`.setAccountMemo('bcca')`

**Comment by quiet-node** [comment]
Hi @moshenskyDV, thanks for the information. We'll look more into this and will provide the fix soon!

**Comment by quiet-node** [comment]
Hello, @moshenskyDV. Thank you for providing the information! It's worth noting that phrases with a the length that's a multiple of 4 are indeed suitable for base64 encoding. This is why the system decodes the 'memo' with the assumption that it's in base64 format, resulting in the appearance of those unusual characters.

We'll look more into this and will provide the fix soon!
