### ISSUE TITLE
Explorer could interpret Solidity method selectors - giving method signature for method calls, other situations

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-mirror-node-explorer#696]
### Problem

Explorer could provide more information for contract calls/returns/results by interpreting fields.  For example, the first 4 bytes of a contract call's calldata is most often a 4-byte encoded method selector.  And it would be great to know what method was being called.

For example, picked at random just now, consider [this contract call](https://hashscan.io/mainnet/transaction/1695254373.390339008?p2=1&k2=1695254445.984780953&p1=1&k1=1695254445.957518951):

<img width="747" alt="image" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/117694041/53c096bb-7f64-4061-b3c9-3e071df695f1">

That leading `618d c65e` in the "input - function & args" hex string is actually a call to `redirectForToken(address,bytes)` - in other words, our HTS token proxy contract.  (Not too interesting in this case, but I _did_ say I picked it at random).  I found that out by [looking here](https://www.4byte.directory/signatures/?bytes4_signature=618dc65e):

<img width="1086" alt="image" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/117694041/5d387c27-29c6-41c5-bce4-6d7599d05ff2">

It would be nice if the explorer would interpret method selectors for me when it could.  Also, events.

### Solution

For various contract byte buffers (hexified) displayed by the Explorer it could find method signatures (or event signatures) in "likely places" (like the first 4 bytes of a calldata) and provide the method name/signature by looking it up in a database.

For example:

`https://4byte.directory` is a public (and open-source) database of Ethereum method selectors (and event selectors).  ([Github repo here](https://github.com/gobitfly/ethereum-function-signature-registry)).  It can be updated manually by a contract's author, or I think Sourcify will do it for you.  Anyway, there are currently ~1.2M signatures in its database.

* And it's not the only Ethereum method selector database out there.  There's also [etherface](https://github.com/volsa/etherface) and others. But considering here only 4byte:

The database itself is unfortunately not directly available.  But given the 4byte API it is easily scrapable.  And given an initial scrape, it can be incrementally scraped for new entries on a schedule (e.g., nightly). (This is explicitly allowed by its license and terms of service, as seen at the bottom of its home page.)

Event signatures are uploaded there too, which would be useful in display Ethereum event logs.

**Comment by ericleponner** [comment]
We are currently working on contract verification.
Once verified, HashScan will use contract ABI to fully decode function calls and contract events.
Your enhancement proposal is to add some decoding smartness even if contract is not verified, right ?

**Comment by david-bakin-sl** [comment]
Yes - method selectors + signatures collected at these sites are (much?) more extensive than those verified.  You could use these sites (or a scrape of the sites) as a fallback.  

I don't know how many (e.g., percentage) of contracts get verified.  Have you seen any numbers on that? (Just curious.)
