### ISSUE TITLE
Token Balances Completely Ignores Tokens with ID values of 0.0.1xxxxxx

### ISSUE THREAD

**Issue by landry314** [hashgraph/hedera-mirror-node-explorer#706]
### Description

When viewing an account and clicking on "Show all token balances" I get to

https://hashscan.io/mainnet/accountbalances/WALLET

and there I can not find any tokens with ID values of 0.0.1xxxxxx

Page 1 starts in 0.0.3xxxxxx and when I get to the last page I am at 0.0.2xxxxxx but it never gets to 0.0.1xxxxxx

In my wallet I have a bunch of tokens with ID values of 0.0.1xxxxxx

### Steps to reproduce

Go to hashscan.io and enter your wallet ID.

Click on "Show all token balances"

Go through every page and notice no tokens in 0.0.1xxxxxx range.

### Hedera network

mainnet

### Version

23.8.0-12

### Operating system

macOS

**Comment by moshenskyDV** [comment]
I agree with issue partially.
I have noticed that not of all associated tokens displayed on `/accountbalances/XXX` tab.

For testing you can use EtaSwap exchange account: [https://hashscan.io/mainnet/accountbalances/0.0.3745835](https://hashscan.io/mainnet/accountbalances/0.0.3745835)
It's associated to 200+ tokens. But hashscan displays only 50.
I believe this is something about querying on backend and not related directly to number pattern (as described by topic starter).
![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/15670713/0d91dc20-a849-4d5a-83b5-ad4afab629eb)

**Comment by landry314** [comment]
ok, using your link above and comparing the two links on my wallet i see that there are tokens in ranges 0.0.7xxxxxx and 0.0.8xxxxxx and 0.0.9xxxxxx which are also not showing up. i also noticed that there are a few in 0.0.20xxxxx. it seems the lowest for me is 0.0.2018575 and highest is 0.0.3633151. it really seems to be a range thing... but i havent done a full comparison of every token. the hashscan token ids are sequential in their return and seem in a subrange of all the token id values.
