### ISSUE TITLE
Smart Contract code verification and interaction in explorer

### ISSUE THREAD

**Issue by walter-hernandez** [hashgraph/hedera-mirror-node-explorer#71]
### Problem

As a developer, I will like to see some of the code of smart contracts to which I may want to add some interactions with my code and/or I just want to interact directly with the code using my wallet

### Solution

For example, Etherscan and Polygonscan allow developers to verify the code associated to their deployed contracts:
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/52283659/169700141-23e74d15-d0a4-49d7-ac36-a05737212ed8.png">

After passing the validation, the smart contract address, for a token, will appear with a blue checkmark showing its verification:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/52283659/169700014-5c18d4a2-126e-4354-920b-d9b95f9ca759.png">

Then, I can read the smart contract code:

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/52283659/169701346-c51bf899-0caf-4f44-aaba-e5c0ec18dd7c.png">

Also, it is possible to interact directly with the contract 
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/52283659/169699904-672b973f-8629-4fce-afa6-a717c74859f5.png">

Options that Hedera can follow for verify the source code of an smart contract are:

- Developer having to submit their source code to verify their deployed smart contracts
- Developer submitting a link to their github repo where the source code is

Then, allow anyone to view the source code and interact with the smart contract from within the explorer using a supported wallet

**Comment by walter-hernandez** [comment]
I am glad to notice in Hedera's roadmap that you are going to implement the suggestion for enhancement on this issue about having an explorer in hashscan / mirror nodes for smart contract verification of solidity code and bytecode:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/52283659/193551071-751b8e31-c517-4d5f-afce-c1f68038c8c2.png">
https://hedera.com/roadmap

I will close this issue once it is implemented

**Comment by SimiHunjan** [comment]
Define user stories @mohsin-hedera

**Comment by SimiHunjan** [comment]
Link to user stories: https://www.notion.so/swirldslabs/Submit-SC-for-verification-7fbe0697a9034244b2cba91fa6ad08fa

**Comment by mohsin-hedera** [comment]
@walter-hernandez thanks for reporting. This has been on our radar as something we want to accomplish. May ping you again to review our initial releases and provide early feedback. Thanks again !!

**Comment by SimiHunjan** [comment]
UI/UX

- Native Sourcify look to start whiles we work on a design for a native mirror nod explorer verification page.
- This allows us to capitalize out of the box features sooner and work through any challenges of a custom solution

cc: @Nana-EC

**Comment by SimiHunjan** [comment]
- Get Docker-Compose solution in place and available on staging for previewnet
- Test testnet resets
