### ISSUE TITLE
Hashscan search result does not show `inactive EVM address` 

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-mirror-node-explorer#711]
### Description

HashScan doesn’t recognize inactive EVM addresses when searching; it returns an error, indicating ‘No Result.’ However, HashScan does display the result if you manually edit the URL by replacing ‘search-result’ with ‘account,’ as shown in the following examples:

When searching: https://hashscan.io/testnet/search-result/0xA4E0d1678578302Afb3Dd6d830b0a84d224Cb29A
After editing the URL: https://hashscan.io/testnet/account/0xA4E0d1678578302Afb3Dd6d830b0a84d224Cb29A

I remember that the search-result used to show inactive EVM address when searching inactive EVM address. 

### Steps to reproduce

1. Search an inactive EVM address on search box such as https://hashscan.io/testnet/search-result/0xA4E0d1678578302Afb3Dd6d830b0a84d224Cb29A
2. Hashscan shows `No Result`
3. Change from `search-result` to `account` https://hashscan.io/testnet/account/0xA4E0d1678578302Afb3Dd6d830b0a84d224Cb29A
4. Hashscan show `inactive EVM address`

Search result should also show `inactive EVM address` 

### Hedera network

mainnet, testnet, previewnet

### Version

latest

### Operating system

None

**Comment by ericleponner** [comment]
Indeed there is a regression here. Thanks for reporting.
