### ISSUE TITLE
Block number not displayed

### ISSUE THREAD

**Issue by tom-hbar** [hashgraph/hedera-mirror-node-explorer#714]
### Description

The block number is not displayed in the UI for some early transactions, for example this one: https://hashscan.io/mainnet/transaction/1568411631.396440000

It appears that hashscan makes a request to the transactions endpoint for the transaction, then queries the blocks endpoint using the consensus_timestamp value to get the block number. The blocks endpoint returns a block for this transaction (block #0), however it isn't displayed in the UI.

transactions endpoint: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?timestamp=1568411631.396440000

blocks endpoint: https://mainnet-public.mirrornode.hedera.com/api/v1/blocks?timestamp=gte:1568411631.396440000&limit=1&order=asc

### Steps to reproduce

1. Go to https://hashscan.io/mainnet/transaction/1568411631.396440000
2. Look at Block value (empty)

### Hedera network

mainnet

### Version

v23.8.0-16-g224465a 

### Operating system

macOS

**Comment by svienot** [comment]
Indeed. The block # is not shown for block 0.
Thanks for reporting this.
