### ISSUE TITLE
Hashscan number of pages on account assets

### ISSUE THREAD

**Issue by hbarusdt** [hashgraph/hedera-mirror-node-explorer#720]
### Problem

Why does hashscan only display up to 4 pages of account assets instead of everything? Can't see the full list of assets

### Solution

Allow viewing of entire list of assets

**Comment by ericleponner** [comment]
Hi @hbarusdt 
Could you give us the account where you are observing the pb ?

**Comment by hbarusdt** [comment]
https://hashscan.io/mainnet/accountbalances/0.0.935559

Here's a sample. There are many more. Can only view the latest 50 token id tokens. Anything beyond that cannot be seen.

**Comment by ericleponner** [comment]
HashScan uses the following mirror node call for retrieving balances:
[https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.935559](https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.935559)
and 50 balances are returned and displayed.

However the other call:
[https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.935559](https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.935559)
reports 99 balances.

Strange…
Let us discuss with mirror node folks and come back.

**Comment by hbarusdt** [comment]
Hi @ericleponner 

Is 99 the maximum retrievable?

**Comment by ericleponner** [comment]
After investigation, it turns out that `api/v1/balances` and `api/v1/accounts` both intentionally return a limited number of balances (50 and 99).
This way to retrieve balances is not now deprecated and should implemented using new API calls.
So we have some work on HashScan side.
Thanks for reporting.

**Comment by hbarusdt** [comment]
Hello @svienot 

I am still only seeing 50 items on hashscan.

**Comment by hbarusdt** [comment]
@svienot I was wondering if hashscan can be updated to reflect the same? 

To update hashscan as @ericleponner pointed out.
