### ISSUE TITLE
Update recent transactions in account flow

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#730]
### Problem

I need to view the transactions related to the users Account. When I click into transactions, after I go to the users account,  and click the back button I get sent to the first page. I want to go back to the page that I was just recently on. This works as expected when navigating transactions from the Transactions tab, but does not work the same when navigating transactions from the Accounts tab.

### Solution

Fix the account level transaction navigation to match that of the Transactions tab.

**Comment by Sheng-Long** [comment]
closing with #754
