### ISSUE TITLE
Users want to associate tokens to their account

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#747]
### Problem

There is request to add the token associate functionality to the explorer. 

As a Hedera account owner, I want to associate a token using one of the supported wallets.
As a Hedera account owner, I want to dissociate a token using one of the supported wallets.

This can be a MetaMask, Blade, or Hashpack wallet.

### Solution

Add support for token associations.

**Comment by svienot** [comment]
A proposed implementation is currently deployed on the DevOps staging server.

 - Once a wallet (any wallet) a connected, a button ASSOCIATE TOKEN or DISSOCIATE TOKEN is displayed:<img width="1045" alt="Screenshot 2024-01-10 at 15 23 33" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/c1ace455-7742-4dce-b306-dc1ddb9e1647">

- When connected to MetaMask, the confirmation dialog allows to choose whether to also import (watch) the token:<img width="791" alt="Screenshot 2024-01-10 at 15 24 01" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/bcab9a29-c2bd-48ef-9ddc-d3f2ad6996bd">

**Comment by SimiHunjan** [comment]
New HIP is in progress

**Comment by svienot** [comment]
This has been addressed by PR #898
