### ISSUE TITLE
Support HNS resolver to Hashscan

### ISSUE THREAD

**Issue by aBFT4LIFE** [hashgraph/hedera-mirror-node-explorer#748]
### Problem

Resolution of HNS names to Hedera account ID's has been broken somewhere along the way on Hashscan over the past 2 months.

Reconnecting the HNS resolution SDK would re-enable this functionality for users to search for Hedera account ID's using HNS names. 

### Solution

https://www.npmjs.com/package/@hedera-name-service/hns-resolution-sdk/v/1.1.5-alhpa.2

**Comment by svienot** [comment]
Hi @aBFT4LIFE - you might be thinking of the Kabuto Name Service, which is the only support for a name service present in HashScan, and which indeed has been broken for a while. Now operational.
We have not had any integration with HNS (yet).

**Comment by aBFT4LIFE** [comment]
Apologies, @svienot I should have been more clear in my initial post, HNS was formerly Hashgraph.name. The TLDs were resolving correctly on Hashscan up until a few months ago and then suddenly stopped working.

**Comment by svienot** [comment]
Would you mind providing an example of name which you were once able to search and no longer works?

**Comment by aBFT4LIFE** [comment]
Any .hbar .boo or .cream name that leverages the HNS resolver and was active.  for Instance branding.hbar would have worked prior to the issue.

**Comment by svienot** [comment]
This is a perfectly valid enhancement request. 
However, I just want to emphasise that we have never implemented such support for HashScan (nor was it provided by the mirror-node) so there is just no way this would have ever worked in HashScan.

**Comment by aBFT4LIFE** [comment]
I see. What are the steps necessary to implement this functionality moving forward?

**Comment by ericleponner** [comment]
@aBFT4LIFE 
I did an integration test : Explorer currently breaks when trying to load [hns-resolution-sdk](https://github.com/hedera-name-service/hns-resolution-sdk).
I filed https://github.com/hedera-name-service/hns-resolution-sdk/issues/3.

**Comment by ericleponner** [comment]
Moving to `hns-resolution-sdk` 2.0.2 enables browser to load HashScan correctly.
However an pb occurs: I filed https://github.com/hedera-name-service/hns-resolution-sdk/issues/4.
