### ISSUE TITLE
Enhance Visibility of Transferred Value in Call Trace on Transaction Page

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#771]
### Problem

Currently, on the transaction page's Call Trace table, the details of value transferred during a call are not displayed at all.

Take for example [this tx](https://hashscan.io/testnet/tx/0xdd26cf29e77de5f6f8cfee31204f761e498379ed68023628dee95bd6258de0fd), I would like to determine the reason why call `1_1_1_8_1_1` fails. I suspect that the function being called is not payable hence the call reverts due to a >0 `msg.value` being set, however I cannot easily confirm this by looking at the details currently displayed.

### Solution

I propose enhancing the Call Trace table on the transaction page to include a clearly labeled and prominent display of the HBAR value that was transferred during each call. This would significantly streamline the user experience by providing immediate clarity on the financial activity within each call.

**Comment by svienot** [comment]
Hi @mshakeg 
 - The call in question is this one:  <img width="1445" alt="Screenshot 2023-11-28 at 16 50 32" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/b7b311e3-517b-4c2d-a19f-7d36483aec99">
 - The corresponding data can be obtained via this mirror-node REST call: `https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0.0.902-1700865371-382511945/actions?index=29`
  - The returned data corresponding to this call is: <img width="928" alt="Screenshot 2023-11-28 at 16 51 57" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/068e9a02-1144-4cef-9956-8a8abae9df00">
 This shows a `value: 0` which would seem to indicate no hbar value was transferred.
 It is not clear which additional data could be displayed...

**Comment by mshakeg** [comment]
@svienot so it would seem that the value transferred in a call is already shown under the `Amount` column, take 1_1_1_12_1_1 in [this transaction](https://hashscan.io/testnet/transaction/1701122793.493297068) as an example.

If the `Amount` displayed is taken from the `value` field we can close this issue, as it should visible even in the case of a revert.

**Comment by svienot** [comment]
Indeed, in your 2nd example, the data returned by the mirror-node for this action is:
```
{
"call_depth": 5,
"call_operation_type": "CALL",
"call_type": "CALL",
"caller": "0.0.5906803",
"caller_type": "CONTRACT",
"from": "0x00000000000000000000000000000000005a2173",
"gas": 3129560,
"gas_used": 207176,
"index": 33,
"input": "0xd87346aaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff804400000000000000000000000000000000000000000000000000000000000d89b4ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff79f0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff80440000000000000000000000000000000000000000000000000000000000000000",
"recipient": "0.0.5990826",
"recipient_type": "CONTRACT",
"result_data": "0x",
"result_data_type": "OUTPUT",
"timestamp": "1701122793.493297068",
"to": "0x00000000000000000000000000000000005b69aa",
"value": 19900717500
}
```
And the amount displayed is `199.00717500 hbar`

**Comment by mshakeg** [comment]
I guess I was looking for a `value` field under the expanded call since that naming is quite typical as opposed to `Amount`, if you don't see any value :) in adding this field or renaming `Amount` to `Value` then you can close this issue.

**Comment by mshakeg** [comment]
@svienot either rename `Amount` to `Value` since developers are used to `value` or add a `value` field somewhere in the expanded view which could be in tinybars(but hbars is fine too)

<img width="1415" alt="expanded call trace" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/40227090/d8ebb937-aede-41ec-8e67-c442dce874a1">

**Comment by svienot** [comment]
@mshakeg - thanks for your constructive (as usual) feedback!
Which would be your preferred option:

1/ `Amount` column renamed to `Value`: <img width="1463" alt="Screenshot 2023-12-12 at 23 11 45" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/e022643e-9703-465d-987c-db028516c541">

2/ 'Value' field explicitly added to the detailed view of the call: <img width="1463" alt="Screenshot 2023-12-12 at 23 17 21" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/a12e75e5-085b-49ba-9bb1-b92b2883c17c">

**Comment by mshakeg** [comment]
thanks @svienot I think option 2, despite it being kind of redundant, but adding a value field as you did doesn't seem to make it crowded imo.
