### ISSUE TITLE
Conflict Between MetaMask and Coinbase Wallet Extensions on HashScan

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#774]
#### What happened:
When both MetaMask and Coinbase Wallet browser extensions are installed and active, attempting to connect MetaMask to HashScan results in an error. The connection fails, and an error modal appears. This issue does not occur when the Coinbase Wallet extension is disabled.

#### Expected Behavior:
I expected HashScan to successfully connect to the MetaMask wallet regardless of the presence of other wallet extensions like Coinbase Wallet. Ideally, users should be able to have multiple wallet extensions installed without experiencing conflicts or connection issues on HashScan.

#### Suggestion for Enhancement

In addition to resolving this conflict, it would be beneficial for HashScan to support direct integration with the Coinbase Wallet.

### Steps to reproduce

1. Ensure both MetaMask and Coinbase Wallet extensions are installed and active in the browser.
2. Navigate to https://hashscan.io/.
3. Attempt to connect to HashScan using the MetaMask wallet.
4. Observe the error modal that appears, indicating a failure to connect.
5. Disable the Coinbase Wallet extension and refresh HashScan.
6. Attempt the connection to HashScan with MetaMask again, which now succeeds.

### Additional context

Screenshot of error modal when attempting to connect metamask with coinbase wallet enabled.

<img width="796" alt="screenshot of metamask failed connection" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/40227090/77ee16f3-fcb5-4c28-9f23-75f82e41df6f">

### Hedera network

testnet

### Version

0fac68f

### Operating system

None

**Comment by ericleponner** [comment]
It looks like it's a [known issue](https://github.com/MetaMask/detect-provider/issues/53) from Metamask's [detect-provider](https://github.com/MetaMask/detect-provider) component.
Coinbase also documents this [problem](https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance) and provides a workaround.
