### ISSUE TITLE
No pending reward displayed- although can be claimed 

### ISSUE THREAD

**Issue by Liebenfiels** [hashgraph/hedera-mirror-node-explorer#794]
### Description

Hi

There is problem with pending reward not been displayed on Hashscan and Acoer ( has the same problem).
I claimed yesterday during day and it did not show anything from past day. When I made transaction today the reward arrived in fact although it was showing pending 0.
Network calculates correctly and there is just display problem on Hashscan as it used to be in the past.
Please take a look
Thank you
Michal

### Steps to reproduce

Check the accounts that have not claimed yet and claimed yesterday

### Hedera network

mainnet

### Version

v23.11.0-13

### Operating system

Windows

**Comment by svienot** [comment]
Regarding pending reward and recent staking rewards, HashScan shows the information provided by the mirror-node without any processing or interpretation, so it is unlikely to be a display problem.
Would you mind explaining more precisely what you have seen exactly,  at each step ?
What do you mean by 'I claimed' ?

**Comment by Liebenfiels** [comment]
I will provide account details to Greg via discord. I have 0 pending rewards as fro now from last 2 days, despite they are there. 
If I  do transaction now it will be deposited. So the display is not correct, it was like that in past. I have not changed any nodes or re-staked as I am saying reward is there just display problem

**Comment by Liebenfiels** [comment]
I would suggest to check the code if it was ready to calculate when % reward dropped now to low 1.03%, maybe is outside of range at code level to calculate at your end as dropped from 2.5% to now 1.03%, 
in case you use something in code such as  IF reward >%x THEN PRINT pending etc (sorry me learning BASIC based on 80s standard hence exmple)

**Comment by Liebenfiels** [comment]
Maybe you need higher longer decimal space precision as you have very low 1.03 % reward per year /365 and per day it is 0.0028%, maybe is rounded to two deciman spaces in calculations and round as 0.00.
Rounding error, double precision needed maybe in total calculations

**Comment by Liebenfiels** [comment]
https://github.com/hashgraph/hedera-mirror-node/issues/7369

**Comment by svienot** [comment]
The mirror-node issue ([#7369](https://github.com/hashgraph/hedera-mirror-node/issues/7369)) has now been fixed and deployed to mainnet. Hence closing this one.
