### ISSUE TITLE
Add support for Brave Wallet

### ISSUE THREAD

**Issue by rbair23** [hashgraph/hedera-mirror-node-explorer#809]
### Problem

We support MetaMask in HashScan. We can also support Brave.

### Solution

Add Brave support just like meta mask.

**Comment by ericleponner** [comment]
Some findings:
- `Brave Wallet` is built directly in the browser
- list of supported chains is also built-in but does not include Hedera for now
- some [discussions](https://community.brave.com/t/please-add-hedera-hashgraph-hbar-to-the-list-of-visible-assets/464570) about adding Hedera to `Brave Wallet` took place a while ago
- nothing explicitly planned for now

**Comment by ericleponner** [comment]
This is implemented by #828.
Closing.
