### ISSUE TITLE
Missing Account 0.0.800 Sender Information for transaction

### ISSUE THREAD

**Issue by mgarbs** [hashgraph/hedera-mirror-node-explorer#810]
### Description

When viewing the transaction details for [a particular transaction](https://hashscan.io/mainnet/transaction/1698908359.650844003) on Hashscan, the sender information is not displayed, despite being available on the [mirror node](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?timestamp=1698908359.650844003). The expected behavior is for the `0.0.800` sender account to be visible in the transaction details. This issue was identified during a review of the Hashscan website and the mirror node data by Discord [user nubeasado in Developer General](https://discord.com/channels/373889138199494658/373889138199494660/1186354830743195649).

### Steps to reproduce

1. Navigate to the transaction on Hashscan [here](https://hashscan.io/mainnet/transaction/1698908359.650844003).
2. Observe the missing sender information in the transaction details (screenshot below)

### Additional context

![image](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/101222532/1024c4b7-9723-4c21-b601-6785294c7b84)
Mirror Node details link showing the correct information: [Mirror Node Details](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?timestamp=1698908359.650844003)
Logs indicating the expected data is available but not displayed on Hashscan.

### Hedera network

mainnet

### Version

v23.11.0

### Operating system

None

**Comment by svienot** [comment]
The missing sender account is in fact `0.0.1859883`, the one initiating the transfer here, and which happens to also get a reward. This is what we should see:
<img width="1456" alt="Screenshot 2023-12-21 at 16 26 23" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/16097111/d07e0ee1-7765-480c-8ceb-b9d904186dd7">
