### ISSUE TITLE
Decode Transaction Call Data for Standard EVM Addresses

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#827]
### Problem

Currently, on the explorer, there is a discrepancy in how transaction call data is displayed for transactions originating from standard EVM EOA addresses versus standard Hedera accounts. Specifically, the transaction call data for standard EVM addresses is displayed as a raw hexadecimal string, which is not user-friendly and requires manual decoding to interpret. In contrast, transactions from Hedera accounts with an account ID evm address show a decoded view of the transaction call data, including the function name and parameters in a structured format.

#### Examples for Reference:

- Call data NOT decoded (standard EVM address): https://hashscan.io/testnet/transaction/1704186823.658538003
- Call data is decoded (Hedera account): https://hashscan.io/testnet/transaction/1704166114.974151786

### Solution

I would like to suggest implementing functionality that would also decode the hexadecimal string for transactions from standard EVM addresses, similar to the decoded display for Hedera account transactions. This feature would significantly improve readability and accessibility for users analyzing transaction details on the explorer.

**Comment by ericleponner** [comment]
This is a bug: both cases should be decoded.
Thanks for reporting @mshakeg
