### ISSUE TITLE
1st item on 2nd page of Token Balances displays bad data

### ISSUE THREAD

**Issue by paulmadsenhbar** [hashgraph/hedera-mirror-node-explorer#87]
### Description

The first item on the 2nd page of the token balance display shows incorrect data , specifically the token name and balance are both wrong

### Steps to reproduce

1. Click on 'Show all Token Balances' for an account with more than 15 tokens
2. Click to get to 2nd page

### Additional context

![screenshot-hashscan io-2022 06 06-10_22_29](https://user-images.githubusercontent.com/106980549/172181322-374e7785-9225-4077-8852-fdf0f85a0661.png)

### Hedera network

mainnet

### Version

v1

### Operating system

Windows

**Comment by ericleponner** [comment]
Thanks for reporting this issue, Paul.
Could you specify the account id matching the snapshot above ?

**Comment by paulmadsenhbar** [comment]
hi Eric, if you email me at paul@hbar.fund I can provide the account number. Id prefer to not disclose to public

**Comment by ericleponner** [comment]
Ok, I reproduced the pb.

**Comment by paulmadsenhbar** [comment]
Fwiw, on my phone the token list doesn't get paginated and the issue
doesn't appear.

**Comment by ericleponner** [comment]
Indeed issue is related to pagination refresh.
