### ISSUE TITLE
Error connecting to Hashpack

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#895]
### Description

There is an error connecting to HashPack. It seems it might be on the HashPack side. This occurred on the staging site.
<img width="769" alt="Screenshot 2024-02-14 at 1 32 47 PM" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/21989138/05e78c56-506c-46d6-9591-99a10b97db4d">

### Steps to reproduce

see above

### Hedera network

other

### Version

na

### Operating system

None

**Comment by SimiHunjan** [comment]
<img width="844" alt="Screenshot 2024-02-14 at 1 36 00 PM" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/21989138/803d793d-ddff-48e1-b2df-71bf6b5be912">

same for Blade

**Comment by svienot** [comment]
This happens from time to time (we do not know how to formally reproduce it).
The connection to wallet extensions is fragile. There is not much we can do about it unfortunately.
We could perhaps, when the error "<wallet> is silent" is returned, display a (i) information icon with a tooltip explaining the best approach to take when this happens, like try to disable/enable the extension, restart Chrome...

**Comment by svienot** [comment]
The procedure to reproduce the issue in a deterministic manner is:
- do a successful connection of the wallet
- disconnect the wallet
- disable the wallet extension and try to reconnect the wallet (right away)
