### ISSUE TITLE
CI: Tag at least a new release every month

### ISSUE THREAD

**Issue by Neurone** [hashgraph/hedera-mirror-node-explorer#899]
### Problem

Other programs rely on the version number of the mirror node explorer to decide when to update their dependencies. If we don't update the release at least every month, or with major changes, those applications continue using the older versions.

One example is our Hedera local node CLI, that today [still refers to a 3-month-old release](https://github.com/hashgraph/hedera-local-node/blob/d180d564f67f9821b070bfece20b0d2afb2b4010/src/configuration/local.json#L7) (v23.11, gcr.io/hedera-registry/hedera-mirror-node-explorer:23.11.0) 

### Solution

Tag the source code with a new release version every month or with any major changes.

**Comment by svienot** [comment]
Duly noted. We just released v24.3.0.
From now on, we'll try to:
 - release at least monthly (around beginning of month)
 - do intermediate releases for important features
 Feel free to ping us when in urgent need for a fix so we can do an ad-hoc intermediate release.
