### ISSUE TITLE
Additional variables for adding network to the static list

### ISSUE THREAD

**Issue by yaroslav-007** [hashgraph/hedera-mirror-node-explorer#933]
### Problem

Hello,

We are currently working on issue [Add support for smart contract verification #558 ](https://github.com/hashgraph/hedera-local-node/issues/558) in local node repo.

We need to be able to manage `sourcifySetup` in `networks-config.json` having as end result:
``` 
   {
        "name": "local",
        "displayName": "LOCALNET",
        "url": "http://localhost:5551/",
        "ledgerID": "03",
        "sourcifySetup": {
          "activate": true,
          "repoURL": "http://localhost:10000/",
          "serverURL": "http://localhost:5002/",
          "verifierURL": "http://localhost:1234/#/",
          "chainID": 298
        }
      }
```

### Solution

As there are already `DOCKER_LOCAL_MIRROR_NODE_MENU_NAME` and `DOCKER_LOCAL_MIRROR_NODE_URL`, it will be very helpful to have environment variables that will enable us to manage the rest of the values.

**Comment by svienot** [comment]
volumes:
      - ./networks-config.json:/app/networks-config.json

**Comment by svienot** [comment]
Hi @yaroslav-007 

We would like to deprecate the use of the `DOCKER_LOCAL_MIRROR_NODE_XXX` variables and instead recommend to use
a mount point allowing to provide a (complete) custom network configuration to the Explorer.

The impact on Local Node would be to include its own `networks-config.json` in its repo and add the definition of a volume 
in its `docker-compose.yml`, something like:

```
volumes:
  - ./networks-config.json:/app/networks-config.json
```

So, assuming you want to keep the same config used by explorer in production (for mainnet, testnet, previewnet)  and add the local node configuration, you can copy the `networks-config.json` used at `<hashscan-url>/networks-config.json` and just add your custom entry for `LOCALNET` to it.

Would that be adequate for you?

**Comment by yaroslav-007** [comment]
Hello @svienot ,

I am currently using the suggested approach.
As you are planing to deprecate the use of the `DOCKER_LOCAL_MIRROR_NODE_XXX` variables, I will close this issues.

Thanks
