### ISSUE TITLE
Provide easy access to ABIs for verified contracts

### ISSUE THREAD

**Issue by vea-vecturne** [hashgraph/hedera-mirror-node-explorer#934]
### Problem

At SaucerSwap, we help people with integration of our smart contracts into their platforms and apps.  We recently noticed that the ABIs for verified contracts were not easily accessible on Hashscan.  It looks like they are still available via downloading the entire source but it's not immediately obvious you can get the metadata.json that way.  When people want to interact with contracts via ethers.js or something similar, the ABI as a file is the easiest way to go.  If they are not smart contract developers, to ask them to checkout and compile our repos is outside of their normal work flow.

### Solution

It would be great if the ABI was more easily accessible to users.  It would also be great if the contract ABI was formatted in the the same way the the compiler outputs them vs metadata.json.   In tutorials, they typically refer to the compiler output when they interact with the deployed smart contract.  I believe this will reduce friction for people that may not be familiar with smart contract development.

### Alternatives

We considered asking them to build the project, but some developers are not familiar with smart contracts and may have difficulty.  This is another point of friction for us and to ask them makes the process more cumbersome.

We considered hosting the ABIs in GitHub but Hashscan should be the source of truth for them since it verifies contracts.

![Screenshot from 2024-03-20 12-34-36](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/95554982/4518166d-c178-4f35-b4ae-819dcc58d979)

https://www.web3.university/tracks/create-a-smart-contract/interact-with-your-smart-contract

**Comment by svienot** [comment]
We are already working (per #782) on the addition of a new `ABI` tab on the ContractDetails page for verified contracts, allowing interactions with the contract. It would make sense to add a download action there.

**Comment by ericleponner** [comment]
@vea-vecturne 
ABI tab is now live on hashscan.io.
Action for downloading ABI will come a bit later.
