### ISSUE TITLE
Add ability to open transactions in new tab

### ISSUE THREAD

**Issue by fessmm** [hashgraph/hedera-mirror-node-explorer#97]
### Problem

Clicking on a transactions opens the transaction on the same page

### Solution

Add option to open in new tab

### Alternatives

right click -> open in new tab

**Comment by svienot** [comment]
The underlying (Oruga) table component does not support dispatching on click+modifier, so we are stuck for now.

**Comment by fessmm** [comment]
"for now" means it will come later or should i close this issue?

**Comment by svienot** [comment]
I have no idea of the likelyhood of this being addressed in Oruga in the near future. On our side, we may consider doing our own custom implementation of the tables but, again, unlikely to happen soon.
So we might as well close the issue.
