### ISSUE TITLE
Cannot mouse wheel click open a tx to get a fresh tab

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#982]
### Description

There are a couple places where you cannot mouse wheel click open a tx to get a fresh tab, this presents a major problem when you have spent scrolling back 25 minutes and cant open a tx in another window, you risk having to open the tx and losing your place and having to go back and spend the next 20 minutes scrolling through history again

Additional Comments: You can sometimes open it, then hit the back button, but believe me if you have spent 45 minutes scrolling back 10,000 pages, you really don't want to risk losing your spot

Discord Feedback: https://discord.com/channels/373889138199494658/1068722201320231062/1230578719895322735

pluto (HashPack)
> There are a couple places where you cannot mousewheel click open a tx to get a fresh tab
this is a really good one that has also bugged me

### Steps to reproduce

Click through many pages ex. to 100+
Try to right click on a transaction and see that you cannot open in a new tab

### Additional context

<img width="1287" alt="Screenshot_2024-04-18_at_11 59 16_AM" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/21989138/0c7f1627-d9fd-4c98-b5ab-e14038c6742e">

### Hedera network

other

### Version

na

### Operating system

None

**Comment by fessmm** [comment]
i also asked for this 2 years ago, at that time there was no support for that.

See https://github.com/hashgraph/hedera-mirror-node-explorer/issues/97

**Comment by svienot** [comment]
We have added a while ago the ability to do Cmd+Click (on Mac) or Ctrl+Click (on Windows) to navigate from table to details in a different tab. 
We should add support for middle/wheel button specifically for Windows since users tend to rely on that in their browser.
