### ISSUE TITLE
Proper decoding of the Precompile contract inputs

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#984]
### Problem

From bugbytes

Discord: https://discord.com/channels/373889138199494658/616725704284962837/1230862128911618048

Comment: one really nice thing that could be improved in hashscan is proper decoding of the Precompile contract inputs?  Particularly 0x0167, it would be very useful for debugging

![image12](https://github.com/hashgraph/hedera-mirror-node-explorer/assets/21989138/5e97317e-3300-4609-97cf-45bc57a9a20e)

### Solution

TBD

**Comment by ericleponner** [comment]
I guess that's close to [#921](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/921).
